// ಕನ್ನಡ strings. Missing keys fall back to English.
const Map<String, String> kn = {
  'nav.home': 'ಮುಖಪುಟ',
  'nav.items': 'ಆಭರಣಗಳು',
  'nav.places': 'ಲಾಕರ್‌ಗಳು',
  'nav.visits': 'ಭೇಟಿಗಳು',
  'nav.more': 'ಇನ್ನಷ್ಟು',

  'common.cancel': 'ರದ್ದುಮಾಡಿ',
  'common.change': 'ಬದಲಿಸಿ',
  'common.date': 'ದಿನಾಂಕ',
  'common.days': 'ದಿನಗಳು',
  'common.edit': 'ತಿದ್ದು',
  'common.invalidNumber': 'ಸರಿಯಾದ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
  'common.ok': 'ಸರಿ',
  'common.other': 'ಇತರೆ',
  'common.required': 'ಅಗತ್ಯವಿದೆ',
  'common.save': 'ಉಳಿಸಿ',
  'common.seeAll': 'ಎಲ್ಲಾ ನೋಡಿ',
  'common.set': 'ಹೊಂದಿಸಿ',
  'common.tapReveal': 'ನೋಡಲು ಒತ್ತಿ',
  'common.time': 'ಸಮಯ',

  'lock.create': '4 ಅಂಕಿಯ PIN ರಚಿಸಿ',
  'lock.confirm': 'PIN ಅನ್ನು ಮತ್ತೊಮ್ಮೆ ನಮೂದಿಸಿ',
  'lock.enter': 'ನಿಮ್ಮ PIN ನಮೂದಿಸಿ',
  'lock.mismatch': 'PIN ಹೊಂದಿಕೆಯಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  'lock.wrong': 'ತಪ್ಪು PIN',
  'lock.wait': 'ಹೆಚ್ಚು ಪ್ರಯತ್ನಗಳು. {s} ಸೆಕೆಂಡ್ ಕಾಯಿರಿ.',
  'lock.bioReason': 'GoldVault ತೆರೆಯಿರಿ',
  'lock.bioAsk': 'ಬೆರಳಚ್ಚು ಅಥವಾ ಮುಖದ ಮೂಲಕ ತೆರೆಯಬೇಕೇ?',
  'lock.bioYes': 'ಹೌದು, ಬೆರಳಚ್ಚು ಬಳಸಿ',
  'lock.bioNo': 'ಬೇಡ, PIN ಮಾತ್ರ',

  'dash.gold': 'ಒಟ್ಟು ಚಿನ್ನ',
  'dash.silver': 'ಒಟ್ಟು ಬೆಳ್ಳಿ',
  'dash.items': 'ಆಭರಣಗಳು',
  'dash.pcs': '{n} ತುಂಡು',
  'dash.value': 'ಅಂದಾಜು ಮೌಲ್ಯ',
  'dash.setRates': 'ದರ ಹೊಂದಿಸಿ',
  'dash.breakdown': 'ವಿಭಾಗವಾರು',
  'dash.byLocation': 'ಸ್ಥಳ',
  'dash.byOwner': 'ಮಾಲೀಕರು',
  'dash.byCategory': 'ಬಗೆ',
  'dash.empty': 'ಇನ್ನೂ ಯಾವುದೇ ಆಭರಣ ಇಲ್ಲ.',
  'dash.itemsN': '{n} ಆಭರಣ',
  'dash.goldShort': 'ಚಿನ್ನ',
  'dash.silverShort': 'ಬೆಳ್ಳಿ',
  'dash.noOwner': 'ಮಾಲೀಕರು ನಮೂದಿಸಿಲ್ಲ',
  'dash.upcoming': 'ಮುಂಬರುವ ಜ್ಞಾಪನೆಗಳು',
  'dash.noReminders': 'ಯಾವುದೂ ಬಾಕಿ ಇಲ್ಲ.',
  'dash.recent': 'ಇತ್ತೀಚಿನ ಚಲನೆಗಳು',
  'dash.noMoves': 'ಇನ್ನೂ ಯಾವುದೇ ಚಲನೆ ಇಲ್ಲ.',

  'rates.title': 'ಚಿನ್ನ ಮತ್ತು ಬೆಳ್ಳಿ ದರ',
  'rates.help': 'ಇಂದಿನ ಪ್ರತಿ ಗ್ರಾಂ ದರ ನಮೂದಿಸಿ. ಮೌಲ್ಯ ಅಂದಾಜಿಗೆ ಮಾತ್ರ; ಇಂಟರ್ನೆಟ್ ಬೇಕಿಲ್ಲ.',
  'rates.gold24': 'ಚಿನ್ನ 24K',
  'rates.silver': 'ಬೆಳ್ಳಿ',
  'rates.platinum': 'ಪ್ಲಾಟಿನಂ',
  'rates.notSet': 'ದರ ಹೊಂದಿಸಿಲ್ಲ – ಇಂದಿನ ದರ ನಮೂದಿಸಲು ಒತ್ತಿ',
  'rates.update': 'ನವೀಕರಿಸಿ',

  'where.title': 'ನನ್ನ ಆಭರಣ ಎಲ್ಲಿದೆ?',
  'where.hint': 'ಹೆಸರು, ಕ್ರಮ ಸಂಖ್ಯೆ, ಮಾಲೀಕರು ಅಥವಾ ಟ್ಯಾಗ್ ಟೈಪ್ ಮಾಡಿ',
  'where.prompt': 'ಕೆಲವು ಅಕ್ಷರ ಟೈಪ್ ಮಾಡಿ, ಉದಾ: "haram" ಅಥವಾ "GV-0012"',
  'where.since': '{date} ರಿಂದ',

  'inv.title': 'ಆಭರಣಗಳು',
  'inv.search': 'ಹೆಸರು, ಕ್ರಮ ಸಂಖ್ಯೆ, ಮಾಲೀಕರು, ಸ್ಥಳ, ಟ್ಯಾಗ್ ಹುಡುಕಿ',
  'inv.sort': 'ವಿಂಗಡಿಸಿ',
  'inv.filters': 'ಫಿಲ್ಟರ್‌ಗಳು',
  'inv.apply': 'ಅನ್ವಯಿಸಿ',
  'inv.clear': 'ತೆರವುಗೊಳಿಸಿ',
  'inv.empty': 'ಇನ್ನೂ ಯಾವುದೇ ಆಭರಣ ಇಲ್ಲ.\nಮೊದಲ ಆಭರಣ ಸೇರಿಸಲು "+ ಆಭರಣ ಸೇರಿಸಿ" ಒತ್ತಿ.',
  'inv.noMatch': 'ನಿಮ್ಮ ಹುಡುಕಾಟಕ್ಕೆ ಹೊಂದುವ ಆಭರಣ ಇಲ್ಲ.',
  'inv.outside': 'ಹೊರಗೆ (ಧರಿಸಿದೆ / ರಿಪೇರಿ / ಸಾಲ / ಅಡವು)',
  'inv.summary': '{n} ಆಭರಣಗಳು · ಒಟ್ಟು {w}',
  'sort.serial': 'ಕ್ರಮ ಸಂಖ್ಯೆ',
  'sort.name': 'ಹೆಸರು',
  'sort.weight': 'ತೂಕ',
  'sort.category': 'ಬಗೆ',
  'sort.location': 'ಸ್ಥಳ',
  'sort.date': 'ಸೇರಿಸಿದ ದಿನಾಂಕ',
  'sort.purchase': 'ಖರೀದಿ ದಿನಾಂಕ',

  'item.add': 'ಆಭರಣ ಸೇರಿಸಿ',
  'add.quick': 'ತ್ವರಿತ ಸೇರ್ಪಡೆ',
  'add.quickSub': 'ಹೆಸರು, ಬಗೆ, ತೂಕ, ಸ್ಥಳ ಮತ್ತು ಫೋಟೋ. ಉಳಿದದ್ದು ನಂತರ.',
  'add.purchase': 'ಹೊಸದಾಗಿ ಖರೀದಿಸಿದ್ದು',
  'add.purchaseSub': 'ಅಂಗಡಿ, ಬಿಲ್, ದರ, ತಯಾರಿಕಾ ಶುಲ್ಕ ಮತ್ತು GST ಸಹಿತ',
  'add.full': 'ಪೂರ್ಣ ವಿವರಗಳು',
  'add.fullSub': 'HUID ಮತ್ತು ಮಾಲೀಕತ್ವ ಸೇರಿ ಎಲ್ಲಾ ವಿವರಗಳು',
  'add.duplicate': 'ಇರುವ ಆಭರಣದ ನಕಲು',
  'add.duplicateSub': 'ಉದಾ: ಜೋಡಿ ಬಳೆಯ ಎರಡನೇ ಬಳೆ',
  'add.pickToCopy': 'ನಕಲು ಮಾಡಲು ಆಭರಣ ಆಯ್ಕೆಮಾಡಿ',
  'add.moreDetails': 'ಈಗಲೇ ಹೆಚ್ಚಿನ ವಿವರ ಸೇರಿಸಿ',
  'add.quickNote': 'ವಿವರಗಳನ್ನು ಯಾವಾಗ ಬೇಕಾದರೂ ನಂತರ ತುಂಬಬಹುದು.',

  'item.serial': 'ಕ್ರಮ ಸಂಖ್ಯೆ',
  'item.name': 'ಆಭರಣದ ಹೆಸರು',
  'item.type': 'ಆಭರಣದ ಬಗೆ',
  'item.category': 'ವರ್ಗ',
  'item.purity': 'ಶುದ್ಧತೆ',
  'item.customPurity': 'ಶುದ್ಧತೆ (ಟೈಪ್ ಮಾಡಿ)',
  'item.pieces': 'ತುಂಡುಗಳು',
  'item.weight': 'ತೂಕ',
  'item.weights': 'ತೂಕ',
  'item.gross': 'ಒಟ್ಟು ತೂಕ',
  'item.net': 'ನಿವ್ವಳ ತೂಕ',
  'item.stone': 'ಕಲ್ಲಿನ ತೂಕ',
  'item.photos': 'ಫೋಟೋಗಳು',
  'item.whereKept': 'ಎಲ್ಲಿ ಇಡಲಾಗಿದೆ?',
  'item.status': 'ಸ್ಥಿತಿ',
  'item.location': 'ಸ್ಥಳ',
  'item.statusNote': 'ಯಾರ ಬಳಿ / ಎಲ್ಲಿ?',
  'item.statusNoteHint': 'ಉದಾ: ಅಮ್ಮ ಧರಿಸಿದ್ದಾರೆ, ಲಲಿತಾ ಜ್ಯುವೆಲರ್ಸ್‌ನಲ್ಲಿ ರಿಪೇರಿ',
  'item.details': 'ವಿವರಗಳು',
  'item.description': 'ವಿವರಣೆ',
  'item.stones': 'ಕಲ್ಲು / ರತ್ನಗಳು',
  'item.huid': 'ಹಾಲ್‌ಮಾರ್ಕ್ / HUID ಸಂಖ್ಯೆ',
  'item.purchase': 'ಖರೀದಿ',
  'item.purchaseDate': 'ಖರೀದಿ ದಿನಾಂಕ',
  'item.shop': 'ಅಂಗಡಿಯ ಹೆಸರು',
  'item.billNo': 'ಬಿಲ್ ಸಂಖ್ಯೆ',
  'item.rate': 'ಪ್ರತಿ ಗ್ರಾಂ ದರ',
  'item.making': 'ತಯಾರಿಕಾ ಶುಲ್ಕ',
  'item.gst': 'GST',
  'item.total': 'ಒಟ್ಟು ಬೆಲೆ',
  'item.calc': 'ಒಟ್ಟು ಲೆಕ್ಕಹಾಕಿ',
  'item.calcNeed': 'ಮೊದಲು ದರ ಮತ್ತು ತೂಕ ನಮೂದಿಸಿ',
  'item.billPhoto': 'ಬಿಲ್ ಫೋಟೋ',
  'item.ownership': 'ಮಾಲೀಕತ್ವ ಮತ್ತು ಟಿಪ್ಪಣಿ',
  'item.owner': 'ಯಾರಿಗೆ ಸೇರಿದ್ದು',
  'item.occasion': 'ಸಂದರ್ಭ',
  'item.giftedBy': 'ಉಡುಗೊರೆ ನೀಡಿದವರು',
  'item.tags': 'ಟ್ಯಾಗ್‌ಗಳು',
  'item.tagsHint': 'ಅಲ್ಪವಿರಾಮದಿಂದ ಬೇರ್ಪಡಿಸಿ, ಉದಾ: ಮದುವೆ, ದಿನನಿತ್ಯ',
  'item.notes': 'ಟಿಪ್ಪಣಿ',
  'item.needLocation': 'ದಯವಿಟ್ಟು ಸ್ಥಳ ಆಯ್ಕೆಮಾಡಿ',
  'item.saved': '{serial} ಆಗಿ ಉಳಿಸಲಾಗಿದೆ',
  'item.edit': 'ಆಭರಣ ತಿದ್ದಿ',
  'item.move': 'ಸ್ಥಳ / ಸ್ಥಿತಿ ಬದಲಿಸಿ',
  'item.dispose': 'ಮಾರಾಟ / ಉಡುಗೊರೆ',
  'item.delete': 'ಅಳಿಸಿ (ತಪ್ಪು ನಮೂದು)',
  'item.deleteWarn': 'ಇದು ಆಭರಣ ಮತ್ತು ಅದರ ಸಂಪೂರ್ಣ ಇತಿಹಾಸವನ್ನು ಅಳಿಸುತ್ತದೆ. ಮಾರಾಟ, ವಿನಿಮಯ ಅಥವಾ ಉಡುಗೊರೆ ನೀಡಿದ್ದರೆ "ಮಾರಾಟ / ಉಡುಗೊರೆ" ಬಳಸಿ – ಇತಿಹಾಸ ಉಳಿಯುತ್ತದೆ.',
  'item.needsDetails': 'ತ್ವರಿತವಾಗಿ ಸೇರಿಸಲಾಗಿದೆ. ಉಳಿದ ವಿವರ ತುಂಬಲು ಒತ್ತಿ.',
  'item.history': 'ಚಲನೆಯ ಇತಿಹಾಸ',

  'status.in_locker': 'ಲಾಕರ್‌ನಲ್ಲಿ',
  'status.at_home': 'ಮನೆಯಲ್ಲಿ',
  'status.worn': 'ಧರಿಸಲಾಗಿದೆ',
  'status.repair': 'ರಿಪೇರಿಗೆ ಕೊಟ್ಟಿದೆ',
  'status.lent': 'ಸಾಲ ಕೊಟ್ಟಿದೆ',
  'status.pledged': 'ಅಡವು ಇಟ್ಟಿದೆ',
  'status.sold': 'ಮಾರಾಟ',
  'status.exchanged': 'ವಿನಿಮಯ',
  'status.gifted': 'ಉಡುಗೊರೆ ನೀಡಲಾಗಿದೆ',

  'move.title': 'ಆಭರಣ ಸ್ಥಳಾಂತರ',
  'move.disposeTitle': 'ಮಾರಾಟ, ವಿನಿಮಯ ಅಥವಾ ಉಡುಗೊರೆ',
  'move.disposeNote': 'ವಿವರ',
  'move.disposeHint': 'ಉದಾ: ಹೊಸ ಸರಕ್ಕೆ ವಿನಿಮಯ, ಪ್ರಿಯಾಗೆ ಉಡುಗೊರೆ',
  'move.disposeConfirm': '"{name}" ಇತಿಹಾಸದಲ್ಲಿ ಉಳಿಯುತ್ತದೆ, ಆದರೆ ಒಟ್ಟು ಲೆಕ್ಕದಲ್ಲಿ ಸೇರುವುದಿಲ್ಲ.',
  'move.visitTip': 'ಸಲಹೆ: ಬ್ಯಾಂಕ್ ಲಾಕರ್‌ನಲ್ಲಿ ಇಡುತ್ತಿದ್ದೀರಾ? ಭೇಟಿಯೂ ದಾಖಲಾಗಲು "ಭೇಟಿ ದಾಖಲಿಸಿ" ಬಳಸಿ.',
  'move.created': 'ಸೇರಿಸಲಾಗಿದೆ – {to}',
  'move.deposit': '{to} ನಲ್ಲಿ ಇಡಲಾಗಿದೆ',
  'move.withdraw': '{from} ನಿಂದ ತೆಗೆಯಲಾಗಿದೆ → {to}',
  'move.close': '{from} ನಿಂದ {to} ಗೆ (ಲಾಕರ್ ಮುಚ್ಚಲಾಗಿದೆ)',
  'move.moved': '{from} ನಿಂದ {to} ಗೆ ಸ್ಥಳಾಂತರ',
  'move.status': 'ಈಗ: {status}',

  'loc.title': 'ಲಾಕರ್ ಮತ್ತು ಸ್ಥಳಗಳು',
  'loc.addLocker': 'ಲಾಕರ್ ಸೇರಿಸಿ',
  'loc.editLocker': 'ಲಾಕರ್ ತಿದ್ದಿ',
  'loc.addPlace': 'ಸ್ಥಳ ಸೇರಿಸಿ (ಉದಾ: ಸಂಬಂಧಿಕರ ಮನೆ)',
  'loc.addSub': 'ಉಪ-ಸ್ಥಳ ಸೇರಿಸಿ',
  'loc.placeName': 'ಹೆಸರು, ಉದಾ: ದೇವರ ಕೋಣೆ ಕಪಾಟು',
  'loc.showClosed': 'ಮುಚ್ಚಿದ ಲಾಕರ್ ತೋರಿಸಿ',
  'loc.closed': 'ಮುಚ್ಚಲಾಗಿದೆ',
  'loc.closedOn': '{date} ರಂದು ಮುಚ್ಚಲಾಗಿದೆ',
  'loc.items': 'ಆಭರಣಗಳು',
  'loc.outside': 'ಮನೆ ಮತ್ತು ಲಾಕರ್‌ನ ಹೊರಗೆ (ಧರಿಸಿದೆ, ರಿಪೇರಿ, ಸಾಲ, ಅಡವು)',
  'loc.bankLocker': 'ಬ್ಯಾಂಕ್ ಲಾಕರ್',
  'loc.place': 'ಸ್ಥಳ',
  'loc.subs': 'ಉಪ-ಸ್ಥಳಗಳು',
  'loc.noSubs': 'ಇನ್ನೂ ಉಪ-ಸ್ಥಳಗಳಿಲ್ಲ.',
  'loc.itemsHere': 'ಇಲ್ಲಿರುವ ಆಭರಣಗಳು',
  'loc.noItems': 'ಈಗ ಇಲ್ಲಿ ಏನೂ ಇಲ್ಲ.',
  'loc.rename': 'ಹೆಸರು ಬದಲಿಸಿ',
  'loc.close': 'ಲಾಕರ್ ಮುಚ್ಚಿ',
  'loc.closeEmpty': 'ಈ ಲಾಕರ್ ಖಾಲಿಯಿದೆ. ಮುಚ್ಚಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಲಾಗುವುದು; ಇತಿಹಾಸ ಉಳಿಯುತ್ತದೆ.',
  'loc.closeMove': 'ಇನ್ನೂ {n} ಆಭರಣಗಳು ಒಳಗಿವೆ. ಮೊದಲು ಅವುಗಳನ್ನು ಎಲ್ಲಿಗೆ ಸ್ಥಳಾಂತರಿಸಬೇಕು ಎಂದು ಆಯ್ಕೆಮಾಡಿ.',
  'loc.moveTo': 'ಆಭರಣಗಳನ್ನು ಇಲ್ಲಿಗೆ ಸ್ಥಳಾಂತರಿಸಿ',
  'loc.closeConfirm': 'ಲಾಕರ್ ಮುಚ್ಚಿ',
  'loc.closedToast': 'ಲಾಕರ್ ಮುಚ್ಚಲಾಗಿದೆ. ಇತಿಹಾಸ ಉಳಿದಿದೆ.',
  'loc.reopen': 'ಮತ್ತೆ ತೆರೆಯಿರಿ',
  'loc.delete': 'ಅಳಿಸಿ',
  'loc.cantDelete': 'ಇಲ್ಲಿ ಆಭರಣ ಅಥವಾ ಇತಿಹಾಸ ಇರುವುದರಿಂದ ಅಳಿಸಲಾಗದು. ಬದಲಿಗೆ ಮುಚ್ಚಿ.',

  'locker.details': 'ಲಾಕರ್ ವಿವರಗಳು',
  'locker.bank': 'ಬ್ಯಾಂಕ್',
  'locker.otherBank': 'ಬ್ಯಾಂಕ್ ಹೆಸರು',
  'locker.name': 'ತೋರಿಸುವ ಹೆಸರು',
  'locker.nameHint': 'ಉದಾ: SBI ಜಯನಗರ ಲಾಕರ್',
  'locker.branch': 'ಶಾಖೆಯ ಹೆಸರು',
  'locker.address': 'ಶಾಖೆಯ ವಿಳಾಸ',
  'locker.number': 'ಲಾಕರ್ ಸಂಖ್ಯೆ',
  'locker.key': 'ಕೀ ಸಂಖ್ಯೆ',
  'locker.size': 'ಲಾಕರ್ ಗಾತ್ರ',
  'locker.opened': 'ಲಾಕರ್ ತೆರೆದ ದಿನಾಂಕ',
  'locker.people': 'ಹೊಂದಿರುವವರು ಮತ್ತು ನಾಮನಿರ್ದೇಶಿತರು',
  'locker.holders': 'ಹೊಂದಿರುವವರ ಹೆಸರು',
  'locker.joint': 'ಜಂಟಿ ಹೊಂದಿರುವವರು',
  'locker.nominee': 'ನಾಮನಿರ್ದೇಶಿತರು',
  'locker.rentSection': 'ಬಾಡಿಗೆ ಮತ್ತು ಸಂಪರ್ಕ',
  'locker.rent': 'ವಾರ್ಷಿಕ ಬಾಡಿಗೆ',
  'locker.rentDue': 'ಬಾಡಿಗೆ ಪಾವತಿ ದಿನಾಂಕ',
  'locker.contact': 'ಬ್ಯಾಂಕ್ ಸಂಪರ್ಕ ಸಂಖ್ಯೆ',
  'locker.colour': 'ಕ್ಯಾಲೆಂಡರ್ ಬಣ್ಣ',
  'locker.autoColour': 'ಬಣ್ಣವನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಆಯ್ಕೆಮಾಡಲಾಗುವುದು.',
  'locker.rentPaid': 'ಬಾಡಿಗೆ ಪಾವತಿಸಲಾಗಿದೆ',
  'locker.rentPaidBody': 'ಮುಂದಿನ ಪಾವತಿ ದಿನಾಂಕ {date} ಆಗಿರುತ್ತದೆ.',

  'visit.title': 'ಲಾಕರ್ ಭೇಟಿಗಳು',
  'visit.log': 'ಭೇಟಿ ದಾಖಲಿಸಿ',
  'visit.logNow': 'ದಾಖಲಿಸಿ',
  'visit.plan': 'ಭೇಟಿ ಯೋಜಿಸಿ',
  'visit.planned': '{date} ಕ್ಕೆ ಭೇಟಿ ಯೋಜಿಸಲಾಗಿದೆ',
  'visit.plannedLegend': 'ಯೋಜಿತ',
  'visit.month': 'ತಿಂಗಳು',
  'visit.week': 'ವಾರ',
  'visit.none': 'ಈ ದಿನ ಯಾವುದೇ ಭೇಟಿ ಇಲ್ಲ.',
  'visit.itemsMoved': '{n} ಚಲನೆ',
  'visit.whatMoved': 'ಈ ದಿನ ಏನೇನು ಚಲಿಸಿತು',
  'visit.locker': 'ಬ್ಯಾಂಕ್ ಲಾಕರ್',
  'visit.timeIn': 'ಒಳಗೆ ಹೋದ ಸಮಯ',
  'visit.timeOut': 'ಹೊರಬಂದ ಸಮಯ',
  'visit.timeOrder': 'ಹೊರಬಂದ ಸಮಯ ಒಳಗೆ ಹೋದ ಸಮಯದ ನಂತರ ಇರಬೇಕು',
  'visit.who': 'ಯಾರು ಭೇಟಿ ನೀಡಿದರು',
  'visit.whoHint': 'ಉದಾ: ಅಪ್ಪ, ಅಮ್ಮ',
  'visit.purpose': 'ಉದ್ದೇಶ',
  'visit.p.deposit': 'ಆಭರಣ ಇಡಲು',
  'visit.p.withdraw': 'ಆಭರಣ ತೆಗೆಯಲು',
  'visit.p.both': 'ಇಡಲು ಮತ್ತು ತೆಗೆಯಲು',
  'visit.p.check': 'ಪರಿಶೀಲನೆ',
  'visit.p.rent': 'ಬಾಡಿಗೆ / ಬ್ಯಾಂಕ್ ಕೆಲಸ',
  'visit.deposited': 'ಲಾಕರ್‌ನಲ್ಲಿ ಇಟ್ಟ ಆಭರಣಗಳು',
  'visit.withdrawn': 'ತೆಗೆದುಕೊಂಡ ಆಭರಣಗಳು',
  'visit.addDeposit': 'ಇಡುವ ಆಭರಣ ಆಯ್ಕೆಮಾಡಿ',
  'visit.addWithdraw': 'ತೆಗೆಯುವ ಆಭರಣ ಆಯ್ಕೆಮಾಡಿ',
  'visit.withdrawWhere': 'ತೆಗೆದ ಆಭರಣಗಳು ಈಗ…',
  'visit.pickLockerFirst': 'ಮೊದಲು ಲಾಕರ್ ಆಯ್ಕೆಮಾಡಿ',
  'visit.saved': 'ಭೇಟಿ ಉಳಿಸಲಾಗಿದೆ · {n} ಆಭರಣ ನವೀಕರಿಸಲಾಗಿದೆ',
  'visit.edit': 'ಭೇಟಿ ತಿದ್ದಿ',
  'visit.editNote': 'ದಿನಾಂಕ, ಸಮಯ ಮತ್ತು ಟಿಪ್ಪಣಿ ಬದಲಿಸಬಹುದು. ಈ ಭೇಟಿಯಲ್ಲಿ ಚಲಿಸಿದ ಆಭರಣಗಳು ಹಾಗೆಯೇ ಉಳಿಯುತ್ತವೆ.',
  'visit.detail': 'ಭೇಟಿ',
  'visit.delete': 'ಭೇಟಿ ಅಳಿಸಿ',
  'visit.noItems': 'ಯಾವುದೂ ಇಲ್ಲ',
  'visit.recent': 'ಇತ್ತೀಚಿನ ಭೇಟಿಗಳು',

  'rem.title': 'ಜ್ಞಾಪನೆಗಳು',
  'rem.add': 'ಜ್ಞಾಪನೆ ಸೇರಿಸಿ',
  'rem.rent': 'ಲಾಕರ್ ಬಾಡಿಗೆ ಬಾಕಿ',
  'rem.notReturned': 'ಇನ್ನೂ ಹಿಂತಿರುಗಿಲ್ಲ',
  'rem.planned': 'ಯೋಜಿತ ಭೇಟಿ',
  'rem.custom': 'ಜ್ಞಾಪನೆ',
  'rem.overdue': 'ಅವಧಿ ಮೀರಿದೆ',
  'rem.outSince': '{date} ರಿಂದ ಹೊರಗಿದೆ',
  'rem.done': 'ಮುಗಿದಿದೆ',
  'rem.rules': 'ಜ್ಞಾಪನೆ ನಿಯಮಗಳು',
  'rem.rulesBody': 'ಆಭರಣ {days} ದಿನ ಲಾಕರ್/ಮನೆಯಿಂದ ಹೊರಗಿದ್ದರೆ ಮತ್ತು ಲಾಕರ್ ಬಾಡಿಗೆಗೆ {lead} ದಿನ ಮುಂಚೆ ನೆನಪಿಸಲಾಗುವುದು.',
  'rem.notReturnedDays': 'ಹಿಂತಿರುಗದಿದ್ದರೆ ನೆನಪಿಸುವ ಅವಧಿ',
  'rem.rentLead': 'ಬಾಡಿಗೆಗೆ ಎಷ್ಟು ಮುಂಚೆ',
  'rem.what': 'ಏನನ್ನು ನೆನಪಿಸಬೇಕು',
  'rem.whatHint': 'ಉದಾ: ರಿಪೇರಿಯಿಂದ ಸರ ತರಬೇಕು',
  'rem.lockerOptional': 'ಲಾಕರ್ (ಯೋಜಿತ ಭೇಟಿಗೆ)',

  'picker.none': 'ಹೊಂದುವ ಆಭರಣ ಇಲ್ಲ.',
  'picker.done': 'ಆಯ್ತು ({n} ಆಯ್ಕೆ)',
  'photo.camera': 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
  'photo.gallery': 'ಗ್ಯಾಲರಿಯಿಂದ ಆಯ್ಕೆಮಾಡಿ',
  'photo.add': 'ಫೋಟೋ ಸೇರಿಸಿ',
  'photo.count': '{max} ರಲ್ಲಿ {n} ಫೋಟೋ · ಆಯ್ಕೆಗಳಿಗೆ ಫೋಟೋವನ್ನು ಒತ್ತಿ ಹಿಡಿಯಿರಿ',
  'photo.countNone': 'ಇನ್ನೂ ಫೋಟೋ ಇಲ್ಲ · ಪ್ರತಿ ಆಭರಣಕ್ಕೆ {max} ವರೆಗೆ',
  'photo.attachBill': 'ಬಿಲ್ ಫೋಟೋ ಲಗತ್ತಿಸಿ',
  'photo.added': '{n} ಫೋಟೋ ಲಗತ್ತಿಸಲಾಗಿದೆ',
  'photo.full': 'ಈಗಾಗಲೇ {max} ಫೋಟೋಗಳಿವೆ. ಹೊಸದನ್ನು ಸೇರಿಸಲು ಒಂದನ್ನು ತೆಗೆಯಿರಿ.',
  'photo.makeMain': 'ಮುಖ್ಯ ಫೋಟೋ ಮಾಡಿ',
  'photo.share': 'ಫೋಟೋ ಹಂಚಿಕೊಳ್ಳಿ',
  'photo.replace': 'ಬದಲಿಸಿ',
  'photo.remove': 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
  'photo.removeBody': 'ಈ ಫೋಟೋವನ್ನು GoldVault ನಿಂದ ಅಳಿಸಲಾಗುವುದು.',

  'set.title': 'ಇನ್ನಷ್ಟು',
  'set.language': 'ಭಾಷೆ',
  'set.general': 'ಸಾಮಾನ್ಯ',
  'set.cloud': 'Google Sheets, ರಫ್ತು ಮತ್ತು ಬ್ಯಾಕಪ್',
  'set.security': 'ಭದ್ರತೆ',
  'set.changePin': 'PIN ಬದಲಿಸಿ',
  'set.currentPin': 'ಈಗಿನ PIN',
  'set.newPin': 'ಹೊಸ PIN',
  'set.confirmPin': 'ಹೊಸ PIN ಮತ್ತೊಮ್ಮೆ',
  'set.pinChanged': 'PIN ಬದಲಾಯಿಸಲಾಗಿದೆ',
  'set.biometric': 'ಬೆರಳಚ್ಚು / ಮುಖ ಗುರುತು',
  'set.biometricSub': 'PIN ಟೈಪ್ ಮಾಡದೆ ತೆರೆಯಿರಿ',
  'set.biometricNA': 'ಈ ಫೋನ್‌ನಲ್ಲಿ ಲಭ್ಯವಿಲ್ಲ',
  'set.blockAll': 'ಎಲ್ಲೆಡೆ ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ತಡೆಯಿರಿ',
  'set.blockAllSub': 'ಆಫ್ ಇದ್ದರೆ, ಮೌಲ್ಯ ಮತ್ತು ಲಾಕರ್ ವಿವರಗಳಿರುವ ಪರದೆಗಳಲ್ಲಿ ಮಾತ್ರ ತಡೆಯಲಾಗುತ್ತದೆ',
  'set.lockNow': 'ಈಗ ಲಾಕ್ ಮಾಡಿ',
  'set.autoLock': 'ಹಿನ್ನೆಲೆಯಲ್ಲಿ 1 ನಿಮಿಷದ ನಂತರ ಸ್ವಯಂ ಲಾಕ್ ಆಗುತ್ತದೆ',
  'set.about': 'ಆ್ಯಪ್ ಬಗ್ಗೆ',
  'set.aboutBody': 'ನಿಮ್ಮ ಮಾಹಿತಿ ಈ ಫೋನ್‌ನಲ್ಲೇ ಗೂಢಲಿಪಿಯ ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ಇರುತ್ತದೆ ಮತ್ತು ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದೆಯೂ ಸಂಪೂರ್ಣವಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ. Google Sheets ಸಿಂಕ್ ಅಥವಾ Google Drive ಬ್ಯಾಕಪ್‌ಗೆ ಮಾತ್ರ ಇಂಟರ್ನೆಟ್ ಬಳಸಲಾಗುತ್ತದೆ.',

  'cloud.title': 'ಸಿಂಕ್, ರಫ್ತು ಮತ್ತು ಬ್ಯಾಕಪ್',
  'cloud.subtitle': 'Google Sheets, Excel, PDF ಮತ್ತು Drive ಬ್ಯಾಕಪ್',
  'cloud.offlineNote': 'ಎಲ್ಲವೂ ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ. ಈ ಸೌಲಭ್ಯಗಳು ನಡೆಯುವಾಗ ಮಾತ್ರ ಇಂಟರ್ನೆಟ್ ಬೇಕು.',
  'cloud.account': 'Google ಖಾತೆ',
  'cloud.signedOut': 'ಸೈನ್ ಇನ್ ಆಗಿಲ್ಲ',
  'cloud.signIn': 'Google ಮೂಲಕ ಸೈನ್ ಇನ್',
  'cloud.signOut': 'ಸೈನ್ ಔಟ್',
  'cloud.signOutBody': 'ಮತ್ತೆ ಸೈನ್ ಇನ್ ಆಗುವವರೆಗೆ ಸ್ವಯಂ ಸಿಂಕ್ ಮತ್ತು ಬ್ಯಾಕಪ್ ನಿಲ್ಲುತ್ತದೆ. ಫೋನ್‌ನಲ್ಲಿರುವ ಮಾಹಿತಿಗೆ ಏನೂ ಆಗುವುದಿಲ್ಲ.',
  'cloud.notConfigured': 'ಈ ಆವೃತ್ತಿಯಲ್ಲಿ Google ಸೈನ್-ಇನ್ ಹೊಂದಿಸಿಲ್ಲ. ಆ್ಯಪ್ ನಿರ್ಮಿಸಿದವರಿಗೆ Google client ID ಸೇರಿಸಲು ಹೇಳಿ (README ನೋಡಿ).',
  'cloud.cancelled': 'ಸೈನ್ ಇನ್ ರದ್ದಾಯಿತು',
  'cloud.signInFailed': 'Google ಸೈನ್ ಇನ್ ವಿಫಲವಾಯಿತು',
  'cloud.offline': 'ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕವಿಲ್ಲ. ಆನ್‌ಲೈನ್ ಆದಾಗ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  'cloud.error': 'ಏನೋ ತಪ್ಪಾಗಿದೆ',

  'sheet.title': 'Google Sheets',
  'sheet.body': 'ಆ್ಯಪ್‌ನಲ್ಲಿರುವುದೇ ಮುಖ್ಯ ಪ್ರತಿ. ನಿಮ್ಮ ಮಾಹಿತಿ "GoldVault Inventory" ಎಂಬ Google Sheet‌ಗೆ (ಮೊದಲ ಸಿಂಕ್‌ನಲ್ಲಿ ರಚನೆ) ಒಂದು ದಿಕ್ಕಿನಲ್ಲಿ ನಕಲಾಗುತ್ತದೆ; ಪ್ರತಿ ಲಾಕರ್‌ಗೆ ಪ್ರತ್ಯೇಕ ಟ್ಯಾಬ್.',
  'sheet.never': 'ಇನ್ನೂ ಸಿಂಕ್ ಆಗಿಲ್ಲ',
  'sheet.last': 'ಕೊನೆಯ ಸಿಂಕ್ {date}',
  'sheet.pending': 'ಸಿಂಕ್‌ಗೆ ಬದಲಾವಣೆಗಳು ಬಾಕಿ ಇವೆ',
  'sheet.auto': 'ಆನ್‌ಲೈನ್ ಆದಾಗ ಸ್ವಯಂ ಸಿಂಕ್',
  'sheet.autoSub': 'ಬದಲಾವಣೆಗಳ ನಂತರ ಹಿನ್ನೆಲೆಯಲ್ಲಿ ಸಿಂಕ್ ಆಗುತ್ತದೆ',
  'sheet.syncNow': 'ಈಗ ಸಿಂಕ್ ಮಾಡಿ',
  'sheet.synced': 'Google Sheet ನವೀಕರಿಸಲಾಗಿದೆ',
  'sheet.share': 'Sheet ಹಂಚಿಕೊಳ್ಳಿ',
  'sheet.email': 'ಇಮೇಲ್ ವಿಳಾಸ',
  'sheet.view': 'ನೋಡಲು ಮಾತ್ರ',
  'sheet.edit': 'ತಿದ್ದಬಹುದು',
  'sheet.shareBtn': 'ಹಂಚಿಕೊಳ್ಳಿ',
  'sheet.sharedWith': '{email} ಜೊತೆ ಹಂಚಿಕೊಳ್ಳಲಾಗಿದೆ',
  'sheet.copyLink': 'Sheet ಲಿಂಕ್ ನಕಲಿಸಿ',
  'sheet.copied': 'ಲಿಂಕ್ ನಕಲಿಸಲಾಗಿದೆ',

  'export.title': 'ರಫ್ತು',
  'export.body': 'Excel ಫೈಲ್ ಅಥವಾ PDF ವರದಿ ರಚಿಸಿ WhatsApp, ಇಮೇಲ್ ಮೂಲಕ ಹಂಚಿಕೊಳ್ಳಿ. ಇಂಟರ್ನೆಟ್ ಬೇಕಿಲ್ಲ.',
  'export.excel': 'Excel (.xlsx) ಗೆ ರಫ್ತು',
  'export.pdf': 'PDF ವರದಿ',

  'backup.title': 'Google Drive ಫೋಲ್ಡರ್ (Google ಸೈನ್ ಇನ್ ಜೊತೆ)',
  'backup.body': 'ಸಂಪೂರ್ಣ ಡೇಟಾಬೇಸ್ ಮತ್ತು ಎಲ್ಲಾ ಫೋಟೋಗಳ ಬ್ಯಾಕಪ್ ನಿಮ್ಮ Google Drive‌ನ "GoldVault Backups" ಫೋಲ್ಡರ್‌ಗೆ. ಕೊನೆಯ 8 ಬ್ಯಾಕಪ್‌ಗಳನ್ನು ಉಳಿಸಲಾಗುತ್ತದೆ.',
  'backup.never': 'ಇನ್ನೂ ಬ್ಯಾಕಪ್ ಆಗಿಲ್ಲ',
  'backup.last': 'ಕೊನೆಯ ಬ್ಯಾಕಪ್: {date}',
  'backup.pass': 'ಪಾಸ್‌ವರ್ಡ್',
  'backup.weekly': 'ಸ್ವಯಂ ವಾರದ ಬ್ಯಾಕಪ್',
  'backup.day': 'ದಿನ',
  'backup.time': 'ಸಮಯ',
  'backup.wifiOnly': 'Wi-Fi ಇದ್ದಾಗ ಮಾತ್ರ',
  'backup.next': 'ಮುಂದಿನ ಬ್ಯಾಕಪ್ ಸುಮಾರು {date}. ಫೋನ್ ಆಫ್‌ಲೈನ್ ಇದ್ದರೆ, ಸಂಪರ್ಕ ಸಿಕ್ಕ ತಕ್ಷಣ ನಡೆಯುತ್ತದೆ.',
  'backup.now': 'ಈಗ ಬ್ಯಾಕಪ್ ಮಾಡಿ',
  'backup.restore': 'Drive ನಿಂದ ಮರುಸ್ಥಾಪಿಸಿ',
  'backup.none': 'Google Drive ನಲ್ಲಿ ಬ್ಯಾಕಪ್ ಸಿಗಲಿಲ್ಲ',
  'backup.choose': 'ಬ್ಯಾಕಪ್ ಆಯ್ಕೆಮಾಡಿ',
  'backup.restoreWarn': 'ಈ ಫೋನ್‌ನ ಎಲ್ಲಾ ಆಭರಣ, ಲಾಕರ್, ಭೇಟಿ ಮತ್ತು ಫೋಟೋಗಳನ್ನು ಬ್ಯಾಕಪ್‌ನಿಂದ ಬದಲಿಸಲಾಗುವುದು. ಮುಂದುವರಿಯಬೇಕೇ?',
  'backup.restoreBtn': 'ಮರುಸ್ಥಾಪಿಸಿ',
  'backup.restored': 'ಮರುಸ್ಥಾಪಿಸಲಾಗಿದೆ · {n} ಆಭರಣಗಳು',
  'backup.err.not_signed_in': 'ಮೊದಲು Google ಮೂಲಕ ಸೈನ್ ಇನ್ ಮಾಡಿ',
  'backup.err.wrong_passphrase': 'ತಪ್ಪು ಬ್ಯಾಕಪ್ ಪಾಸ್‌ವರ್ಡ್',
  'backup.err.bad_file': 'ಇದು ಮಾನ್ಯ GoldVault ಬ್ಯಾಕಪ್ ಅಲ್ಲ',

  'notif.rent': 'ಲಾಕರ್ ಬಾಡಿಗೆ ಬಾಕಿ: {name}',
  'notif.rentBody': '{date} ರಂದು ಪಾವತಿಸಬೇಕು {amount}',
  'notif.notReturned': 'ಆಭರಣ ಇನ್ನೂ ಹಿಂತಿರುಗಿಲ್ಲ',
  'notif.notReturnedBody': '{name} {date} ರಿಂದ ಹೊರಗಿದೆ',
  'notif.planned': 'ಯೋಜಿತ ಲಾಕರ್ ಭೇಟಿ: {name}',
  'notif.plannedBody': '{date} ರಂದು',
  'notif.backupDone': 'GoldVault ಬ್ಯಾಕಪ್ ಪೂರ್ಣಗೊಂಡಿದೆ',
  'notif.backupFailed': 'GoldVault ಬ್ಯಾಕಪ್‌ಗೆ ಗಮನ ಬೇಕು',

  'opt.SBI': 'SBI',
  'opt.HDFC': 'HDFC',
  'opt.ICICI': 'ICICI',
  'opt.Axis': 'ಆಕ್ಸಿಸ್',
  'opt.Canara': 'ಕೆನರಾ',
  'opt.Union Bank': 'ಯೂನಿಯನ್ ಬ್ಯಾಂಕ್',
  'opt.Bank of Baroda': 'ಬ್ಯಾಂಕ್ ಆಫ್ ಬರೋಡಾ',
  'opt.Karnataka Bank': 'ಕರ್ಣಾಟಕ ಬ್ಯಾಂಕ್',
  'opt.Other': 'ಇತರೆ',
  'opt.Small': 'ಸಣ್ಣ',
  'opt.Medium': 'ಮಧ್ಯಮ',
  'opt.Large': 'ದೊಡ್ಡ',
  'opt.Extra Large': 'ಅತಿ ದೊಡ್ಡ',
  'opt.Gold': 'ಚಿನ್ನ',
  'opt.Silver': 'ಬೆಳ್ಳಿ',
  'opt.Diamond': 'ವಜ್ರ',
  'opt.Platinum': 'ಪ್ಲಾಟಿನಂ',
  'opt.Necklace': 'ನೆಕ್ಲೇಸ್',
  'opt.Long chain (Haram)': 'ಉದ್ದ ಸರ (ಹಾರ)',
  'opt.Chain': 'ಸರ',
  'opt.Mangalsutra': 'ಮಾಂಗಲ್ಯ ಸರ',
  'opt.Bangle': 'ಬಳೆ',
  'opt.Bracelet': 'ಕಡಗ',
  'opt.Ring': 'ಉಂಗುರ',
  'opt.Earrings': 'ಕಿವಿಯೋಲೆ',
  'opt.Jhumka': 'ಜುಮುಕಿ',
  'opt.Nose pin': 'ಮೂಗುತಿ',
  'opt.Anklet': 'ಕಾಲ್ಗೆಜ್ಜೆ',
  'opt.Toe ring': 'ಕಾಲುಂಗುರ',
  'opt.Waist belt (Vaddanam)': 'ಒಡ್ಯಾಣ',
  'opt.Pendant': 'ಪದಕ',
  'opt.Coin': 'ನಾಣ್ಯ',
  'opt.Bar': 'ಬಿಸ್ಕತ್ / ಬಾರ್',
  'opt.Idol': 'ವಿಗ್ರಹ',
  'opt.Utensil': 'ಪಾತ್ರೆ',
  'opt.Pooja item': 'ಪೂಜಾ ಸಾಮಗ್ರಿ',
  'opt.Watch': 'ಗಡಿಯಾರ',

  // alarms, bank holidays, display settings
  'common.nDays': '{n} ದಿನ',
  'dash.outNow': 'ಈಗ ಹೊರಗಿರುವವು',
  'visit.logTab': 'ಭೇಟಿ ದಾಖಲೆ',
  'visit.remindBack': 'ಹಿಂದಿರುಗಿ ಇಡಲು ನೆನಪಿಸಿ',
  'visit.remindBackSub': 'ಈ ಆಭರಣಗಳನ್ನು ಮತ್ತೆ ಲಾಕರ್‌ನಲ್ಲಿ ಇಡಲು ಅಲಾರಂ',
  'set.display': 'ತೋರಿಕೆ',
  'set.showValues': 'ಇಂದಿನ ದರ ಮತ್ತು ಅಂದಾಜು ಮೌಲ್ಯ ತೋರಿಸಿ',
  'set.showValuesSub': 'ಆಫ್: ಚಿನ್ನ/ಬೆಳ್ಳಿ ದರ ಮತ್ತು ಮೌಲ್ಯ ಎಲ್ಲೆಡೆ ಮರೆಯಾಗುತ್ತದೆ (ಆ್ಯಪ್, PDF, Excel, Sheets)',
  'set.dashBreakdown': 'ಮುಖಪುಟ: ವಿಭಾಗವಾರು',
  'set.dashReminders': 'ಮುಖಪುಟ: ಮುಂಬರುವ ಜ್ಞಾಪನೆಗಳು',
  'set.dashRecent': 'ಮುಖಪುಟ: ಇತ್ತೀಚಿನ ಚಲನೆಗಳು',
  'set.autoLockAfter': 'ಸ್ವಯಂ ಲಾಕ್ ಸಮಯ',
  'set.seconds': '{n} ಸೆಕೆಂಡ್',
  'set.minutes': '{n} ನಿಮಿಷ',
  'alerts.title': 'ಎಚ್ಚರಿಕೆ ಮತ್ತು ಅಲಾರಂ',
  'alerts.sub': 'ಪ್ರತಿ ಜ್ಞಾಪನೆ, ಅಲಾರಂ, ರಜೆ ಎಚ್ಚರಿಕೆಯನ್ನು ಆನ್/ಆಫ್ ಮಾಡಿ',
  'alerts.general': 'ಸಾಮಾನ್ಯ',
  'alerts.master': 'ಎಲ್ಲಾ ಅಧಿಸೂಚನೆ ಮತ್ತು ಅಲಾರಂ',
  'alerts.masterSub': 'ಕೆಳಗಿನ ಎಲ್ಲದಕ್ಕೂ ಮುಖ್ಯ ಸ್ವಿಚ್',
  'alerts.time': 'ಎಚ್ಚರಿಕೆ ಸಮಯ',
  'alerts.timeSub': 'ಬಾಡಿಗೆ, ರಜೆ ಮುಂತಾದ ದಿನಾಂಕ ಮಾತ್ರ ಇರುವ ಎಚ್ಚರಿಕೆಗಳ ಸಮಯ',
  'alerts.alarmDefault': 'ಹೊಸ ಜ್ಞಾಪನೆಗಳು ಅಲಾರಂನಂತೆ ರಿಂಗ್ ಆಗಲಿ',
  'alerts.exact': 'ನಿಖರ ಸಮಯದ ಅಲಾರಂಗೆ ಅನುಮತಿ',
  'alerts.exactSub': 'ಕೆಲವು ಫೋನ್‌ಗಳಲ್ಲಿ ಅಲಾರಂ ಸರಿಯಾದ ಸಮಯಕ್ಕೆ ರಿಂಗ್ ಆಗಲು ಬೇಕು',
  'alerts.test': 'ಪರೀಕ್ಷಾ ಅಲಾರಂ',
  'alerts.testSub': '1 ನಿಮಿಷದಲ್ಲಿ ರಿಂಗ್ ಆಗುತ್ತದೆ, ಶಬ್ದ ಪರಿಶೀಲಿಸಿ',
  'alerts.testSet': 'ಪರೀಕ್ಷಾ ಅಲಾರಂ 1 ನಿಮಿಷದಲ್ಲಿ ರಿಂಗ್ ಆಗುತ್ತದೆ',
  'alerts.testTitle': 'GoldVault ಪರೀಕ್ಷಾ ಅಲಾರಂ',
  'alerts.testBody': 'ಅಲಾರಂ ಕೆಲಸ ಮಾಡುತ್ತಿದೆ.',
  'alerts.lockers': 'ಲಾಕರ್ ಮತ್ತು ಆಭರಣಗಳು',
  'alerts.rent': 'ಲಾಕರ್ ಬಾಡಿಗೆ ಬಾಕಿ',
  'alerts.planned': 'ಯೋಜಿತ ಭೇಟಿಗಳು',
  'alerts.plannedLead': 'ಭೇಟಿಗೆ ಎಷ್ಟು ದಿನ ಮುಂಚೆ',
  'alerts.notReturned': 'ಹಿಂತಿರುಗದ ಆಭರಣಗಳು',
  'alerts.holiday': 'ಬ್ಯಾಂಕ್ ರಜೆಗೆ ಮುಂಚೆ ಎಚ್ಚರಿಸಿ',
  'alerts.holidaySub': 'ಬ್ಯಾಂಕ್ ಮುಚ್ಚುವ ಮೊದಲು ಆಭರಣ ತೆಗೆದುಕೊಳ್ಳಲು ನೆನಪಿಸುತ್ತದೆ',
  'alerts.holidayLead': 'ಎಷ್ಟು ದಿನ ಮುಂಚೆ',
  'alerts.holidayWeekends': '2ನೇ ಮತ್ತು 4ನೇ ಶನಿವಾರ + ಭಾನುವಾರ ಬ್ಯಾಂಕ್ ರಜೆ',
  'alerts.other': 'ಇತರೆ',
  'alerts.backup': 'ಬ್ಯಾಕಪ್ ಮುಗಿದ ಅಧಿಸೂಚನೆ',
  'alerts.allOff': 'ಎಲ್ಲಾ ಅಧಿಸೂಚನೆ ಮತ್ತು ಅಲಾರಂ ಆಫ್ ಆಗಿವೆ. ಬದಲಿಸಲು ಒತ್ತಿ.',
  'bank.today': 'ಇಂದು',
  'bank.tomorrow': 'ನಾಳೆ',
  'bank.open': 'ತೆರೆದಿದೆ',
  'bank.closed': 'ಮುಚ್ಚಿದೆ',
  'bank.opensOn': 'ಬ್ಯಾಂಕ್ ಮತ್ತೆ ತೆರೆಯುವುದು: {date}',
  'bank.todayShort': 'ಇಂದು',
  'bank.tomorrowShort': 'ನಾಳೆ',
  'bank.days': 'ದಿನ',
  'hol.title': 'ಬ್ಯಾಂಕ್ ರಜೆಗಳು',
  'hol.add': 'ರಜೆ ಸೇರಿಸಿ',
  'hol.edit': 'ರಜೆ ತಿದ್ದಿ',
  'hol.addHere': 'ಈ ದಿನ ರಜೆ ಸೇರಿಸಿ',
  'hol.delete': 'ರಜೆ ಅಳಿಸಿ',
  'hol.name': 'ರಜೆಯ ಹೆಸರು',
  'hol.nameHint': 'ಉದಾ: ಯುಗಾದಿ, ಆಯುಧ ಪೂಜೆ, ದೀಪಾವಳಿ',
  'hol.everyYear': 'ಪ್ರತಿ ವರ್ಷ',
  'hol.everyYearSub': 'ಪ್ರತಿ ವರ್ಷ ಅದೇ ದಿನಾಂಕ (ಉದಾ: ಗಣರಾಜ್ಯೋತ್ಸವ)',
  'hol.on': 'ಈ ದಿನ ಬ್ಯಾಂಕ್ ಮುಚ್ಚಿರುತ್ತದೆ',
  'hol.off': 'ಆಫ್ ಮಾಡಲಾಗಿದೆ',
  'hol.open': 'ಬ್ಯಾಂಕ್ ತೆರೆದಿದೆ',
  'hol.closed': 'ಬ್ಯಾಂಕ್ ಮುಚ್ಚಿದೆ',
  'hol.closedDays': 'ಬ್ಯಾಂಕ್ {n} ದಿನ ಮುಚ್ಚಿರುತ್ತದೆ',
  'hol.closedThatDay': 'ಈ ದಿನ ಬ್ಯಾಂಕ್ ಮುಚ್ಚಿರುತ್ತದೆ: {why}',
  'hol.alertOn': '{date} ರಂದು ಎಚ್ಚರಿಕೆ',
  'hol.alertsOff': 'ರಜೆ ಎಚ್ಚರಿಕೆಗಳು ಆಫ್ ಆಗಿವೆ (ಎಚ್ಚರಿಕೆ ಮತ್ತು ಅಲಾರಂ).',
  'hol.legendHoliday': 'ಬ್ಯಾಂಕ್ ರಜೆ',
  'hol.legendWeekend': 'ಭಾನುವಾರ / 2ನೇ ಮತ್ತು 4ನೇ ಶನಿವಾರ (ಬ್ಯಾಂಕ್ ಮುಚ್ಚಿರುತ್ತದೆ)',
  'hol.upcoming': 'ಮುಂಬರುವ ರಜೆಗಳು',
  'hol.noneUpcoming': 'ಮುಂದಿನ 4 ತಿಂಗಳಲ್ಲಿ ಬ್ಯಾಂಕ್ ರಜೆ ಇಲ್ಲ.',
  'hol.remindTake': 'ಇದಕ್ಕೂ ಮುನ್ನ ಆಭರಣ ತೆಗೆಯಲು ಅಲಾರಂ',
  'hol.list': 'ರಜೆ ಪಟ್ಟಿ',
  'hol.listHelp': 'ನಿಗದಿತ ದಿನಾಂಕದ ರಜೆಗಳನ್ನು ಸೇರಿಸಲಾಗಿದೆ. ಹಬ್ಬಗಳ ದಿನಾಂಕ ಪ್ರತಿ ವರ್ಷ ಬದಲಾಗುತ್ತದೆ, ಆದ್ದರಿಂದ ನಿಮ್ಮ ಬ್ಯಾಂಕ್‌ನ ರಜೆ ಪಟ್ಟಿಯಿಂದ ಸೇರಿಸಿ. ಯಾವುದೇ ರಜೆಯನ್ನು ಆಫ್ ಮಾಡಬಹುದು.',
  'hol.ruleSundays': 'ಎಲ್ಲಾ ಭಾನುವಾರ ಬ್ಯಾಂಕ್ ಮುಚ್ಚಿರುತ್ತದೆ',
  'hol.ruleSaturdays': '2ನೇ ಮತ್ತು 4ನೇ ಶನಿವಾರ ಬ್ಯಾಂಕ್ ಮುಚ್ಚಿರುತ್ತದೆ',
  'hol.onVisitCal': 'ಭೇಟಿ ಕ್ಯಾಲೆಂಡರ್‌ನಲ್ಲಿ ಬ್ಯಾಂಕ್ ರಜೆ ತೋರಿಸಿ',
  'hol.weekend': 'ವಾರಾಂತ್ಯ',
  'hol.sun': 'ಭಾನುವಾರ',
  'hol.sat2': '2ನೇ ಶನಿವಾರ',
  'hol.sat4': '4ನೇ ಶನಿವಾರ',
  'notif.keep': 'ಆಭರಣವನ್ನು ಮತ್ತೆ ಲಾಕರ್‌ನಲ್ಲಿ ಇಡಿ',
  'notif.take': 'ಲಾಕರ್‌ನಿಂದ ಆಭರಣ ತೆಗೆದುಕೊಳ್ಳಿ',
  'notif.holiday': '{date} ರಿಂದ {n} ದಿನ ಬ್ಯಾಂಕ್ ಮುಚ್ಚಿರುತ್ತದೆ',
  'notif.holidayBody': '{what} ({range}). ಬೇಕಾದ ಆಭರಣವನ್ನು ಅದಕ್ಕೂ ಮುನ್ನ ತೆಗೆದುಕೊಳ್ಳಿ.',
  'rem.titleSub': 'ಆಭರಣ ಇಡಲು / ತೆಗೆಯಲು ಅಲಾರಂ, ಯೋಜಿತ ಭೇಟಿಗಳು',
  'rem.mine': 'ನನ್ನ ಅಲಾರಂ ಮತ್ತು ಜ್ಞಾಪನೆಗಳು',
  'rem.mineEmpty': 'ಇನ್ನೂ ಅಲಾರಂ ಇಲ್ಲ. ಹೊಂದಿಸಲು "ಜ್ಞಾಪನೆ ಸೇರಿಸಿ" ಒತ್ತಿ.',
  'rem.auto': 'ಸ್ವಯಂ ಎಚ್ಚರಿಕೆಗಳು',
  'rem.holiday': 'ಬ್ಯಾಂಕ್ ರಜೆ',
  'rem.edit': 'ಜ್ಞಾಪನೆ ತಿದ್ದಿ',
  'rem.delete': 'ಜ್ಞಾಪನೆ ಅಳಿಸಿ',
  'rem.type': 'ಇದು ಯಾವುದಕ್ಕೆ?',
  'rem.kind.keep': 'ಲಾಕರ್‌ನಲ್ಲಿ ಇಡಲು',
  'rem.kind.take': 'ಲಾಕರ್‌ನಿಂದ ತೆಗೆಯಲು',
  'rem.kind.planned_visit': 'ಲಾಕರ್ ಭೇಟಿ',
  'rem.kind.custom': 'ಇತರೆ',
  'rem.locker': 'ಲಾಕರ್',
  'rem.titleAuto': 'ಖಾಲಿ ಬಿಟ್ಟರೆ ಸ್ವಯಂ ಶೀರ್ಷಿಕೆ',
  'rem.theLocker': 'ಲಾಕರ್',
  'rem.keepTitle': '{where} ನಲ್ಲಿ ಆಭರಣ ಇಡಿ',
  'rem.takeTitle': '{where} ನಿಂದ ಆಭರಣ ತೆಗೆಯಿರಿ',
  'rem.repeat': 'ಪುನರಾವರ್ತನೆ',
  'rem.repeat.none': 'ಪುನರಾವರ್ತನೆ ಇಲ್ಲ',
  'rem.repeat.weekly': 'ಪ್ರತಿ ವಾರ',
  'rem.repeat.monthly': 'ಪ್ರತಿ ತಿಂಗಳು',
  'rem.repeat.yearly': 'ಪ್ರತಿ ವರ್ಷ',
  'rem.items': 'ಆಭರಣಗಳು',
  'rem.chooseItems': 'ಆಭರಣ ಆಯ್ಕೆಮಾಡಿ (ಐಚ್ಛಿಕ)',
  'rem.keepAutoDone': 'ಈ ಆಭರಣಗಳನ್ನು ಲಾಕರ್‌ನಲ್ಲಿ ಇಟ್ಟಾಗ ಸ್ವಯಂ ಮುಗಿದಂತೆ ಗುರುತಿಸಲಾಗುತ್ತದೆ.',
  'rem.alarm': 'ಅಲಾರಂನಂತೆ ರಿಂಗ್ ಆಗಲಿ',
  'rem.alarmSub': 'ತೆರೆಯುವವರೆಗೆ ಜೋರಾಗಿ ರಿಂಗ್ ಆಗುತ್ತಲೇ ಇರುತ್ತದೆ',
  'rem.enabled': 'ಜ್ಞಾಪನೆ ಆನ್',
  'rem.saved': '{when} ಕ್ಕೆ ಜ್ಞಾಪನೆ ಹೊಂದಿಸಲಾಗಿದೆ',

  // time out of locker / return-by
  'dur.justNow': 'ಈಗಷ್ಟೇ',
  'dur.days': '{n} ದಿನ',
  'dur.hours': '{n} ಗಂಟೆ',
  'dur.mins': '{n} ನಿಮಿಷ',
  'ret.title': 'ಹಿಂದಿರುಗಿಸುವ ಅಲಾರಂ',
  'ret.sub': 'ಐಚ್ಛಿಕ: ಈ ಆಭರಣವನ್ನು ಮತ್ತೆ ಲಾಕರ್‌ನಲ್ಲಿ ಇಡಲು ಅಲಾರಂ',
  'ret.date': 'ಹಿಂದಿರುಗಿಸುವ ದಿನಾಂಕ',
  'ret.untilBack': 'ಮತ್ತೆ ಇಡುವವರೆಗೆ ಪ್ರತಿದಿನ ನೆನಪಿಸಿ',
  'ret.untilBackSub': 'ದಿನಾಂಕ ಕಳೆದ ನಂತರ, ಲಾಕರ್‌ನಲ್ಲಿ ಇಡುವವರೆಗೆ ಅಲಾರಂ ಪ್ರತಿದಿನ ರಿಂಗ್ ಆಗುತ್ತದೆ',
  'ret.outFor': 'ಹೊರಗೆ: {d}',
  'ret.by': '{date} ಒಳಗೆ ಹಿಂದಿರುಗಿಸಿ',
  'ret.overdue': '{date} ರಿಂದ ಬಾಕಿ',
  'ret.takenOutOn': 'ಲಾಕರ್‌ನಿಂದ ತೆಗೆದದ್ದು: {date}',
  'ret.setAlarm': 'ಹಿಂದಿರುಗಿಸುವ ಅಲಾರಂ ಹೊಂದಿಸಿ',
  'ret.screen': 'ಹೊರತೆಗೆದವು',
  'ret.screenSub': 'ಪ್ರತಿ ಆಭರಣ ಲಾಕರ್‌ನಿಂದ ಎಷ್ಟು ಸಮಯ ಹೊರಗಿದೆ',
  'ret.none': 'ಎಲ್ಲವೂ ಲಾಕರ್‌ಗಳಲ್ಲಿವೆ.',
  'ret.summary': '{n} ಆಭರಣಗಳು ಲಾಕರ್‌ನಿಂದ ಹೊರಗಿವೆ',
  'ret.lateN': '{n} ಬಾಕಿ',
  'ret.askDefault': 'ಹಿಂದಿರುಗಿಸುವ ಅಲಾರಂ ಸಾಮಾನ್ಯವಾಗಿ ಆನ್',
  'ret.askDefaultSub': 'ಆಭರಣ ತೆಗೆಯುವಾಗ ಹಿಂದಿರುಗಿಸುವ ಅಲಾರಂ ಆನ್ ಆಗಿರುತ್ತದೆ',
  'ret.defaultDays': 'ಸಾಮಾನ್ಯ ಹಿಂದಿರುಗಿಸುವ ಅವಧಿ',
  'set.showOutTime': 'ಆಭರಣ ಎಷ್ಟು ಸಮಯ ಹೊರಗಿದೆ ತೋರಿಸಿ',
  'set.showOutTimeSub': 'ಆಭರಣ ಕಾರ್ಡ್‌ಗಳಲ್ಲಿ "3 ದಿನದಿಂದ ಹೊರಗಿದೆ"',
  'rem.repeat.until_back': 'ಮತ್ತೆ ಇಡುವವರೆಗೆ ಪ್ರತಿದಿನ',
  'rem.repeat.daily': 'ಪ್ರತಿದಿನ',

  // multiple alarm options
  'alert.options': 'ಅಲಾರಂ ಆಯ್ಕೆಗಳು',
  'alert.alertMe': 'ಯಾವಾಗ ನೆನಪಿಸಬೇಕು',
  'alert.atTime': 'ಆ ಸಮಯಕ್ಕೆ',
  'alert.before': '{x} ಮುಂಚೆ',
  'alert.inX': '{x} ನಲ್ಲಿ',
  'alert.custom': 'ಬೇರೆ…',
  'alert.mins': '{n} ನಿಮಿಷ',
  'alert.hours': '{n} ಗಂಟೆ',
  'alert.days': '{n} ದಿನ',
  'alert.weeks': '{n} ವಾರ',
  'alert.unit.min': 'ನಿಮಿಷ ಮುಂಚೆ',
  'alert.unit.hour': 'ಗಂಟೆ ಮುಂಚೆ',
  'alert.unit.day': 'ದಿನ ಮುಂಚೆ',
  'alert.unit.week': 'ವಾರ ಮುಂಚೆ',
  'alert.sound': 'ಶಬ್ದ',
  'alert.sound.alarm': 'ಅಲಾರಂ',
  'alert.sound.notify': 'ಶಬ್ದ',
  'alert.sound.silent': 'ಮೌನ',
  'alert.soundHelp.alarm': 'ಅಲಾರಂ ಧ್ವನಿ; ತೆರೆಯುವವರೆಗೆ ರಿಂಗ್ ಆಗುತ್ತಲೇ ಇರುತ್ತದೆ',
  'alert.soundHelp.notify': 'ಸಾಮಾನ್ಯ ಅಧಿಸೂಚನೆ ಶಬ್ದ, ಒಮ್ಮೆ',
  'alert.soundHelp.silent': 'ಶಬ್ದವಿಲ್ಲದೆ ತೋರಿಸುತ್ತದೆ (ಆನ್ ಇದ್ದರೆ ಕಂಪನ ಮಾತ್ರ)',
  'alert.vibrate': 'ಕಂಪನ',
  'alert.snooze': 'ಸ್ನೂಜ್ ಬಟನ್',
  'alert.snoozeOff': 'ಆಫ್',
  'alert.defaults': 'ಸಾಮಾನ್ಯ ಅಲಾರಂ ಆಯ್ಕೆಗಳು',
  'alert.defaultsSub': 'ಹೊಸ ಜ್ಞಾಪನೆಗಳಿಗೆ ಸಮಯ, ಶಬ್ದ, ಕಂಪನ ಮತ್ತು ಸ್ನೂಜ್',
  'alert.forItem': 'ಈ ಆಭರಣದ ಅಲಾರಂಗಳು',
  'alert.noneForItem': 'ಈ ಆಭರಣಕ್ಕೆ ಇನ್ನೂ ಅಲಾರಂ ಇಲ್ಲ.',
  'alert.nAlerts': '{n} ಎಚ್ಚರಿಕೆಗಳು',
  'notif.snooze': '{n} ನಿಮಿಷ ಸ್ನೂಜ್',
  'notif.done': 'ಆಯ್ತು',

  // any number of days
  'dur.months': '{n} ತಿಂಗಳು',
  'dur.years': '{n} ವರ್ಷ',
  'alert.months': '{n} ತಿಂಗಳು',
  'alert.unit.month': 'ತಿಂಗಳು ಮುಂಚೆ',
  'rem.repeat.everyN': 'ಪ್ರತಿ {n}',
  'rem.repeat.everyNPick': 'ಪ್ರತಿ … ದಿನಕ್ಕೊಮ್ಮೆ (ಆಯ್ಕೆಮಾಡಿ)',
  'ret.after': 'ಎಷ್ಟು ದಿನದ ನಂತರ ಹಿಂದಿರುಗಿಸಬೇಕು',
  'ret.otherDays': 'ಬೇರೆ…',

  // calendar alarms, home toggles
  'dash.addAlarm': 'ಅಲಾರಂ ಸೇರಿಸಿ',
  'dash.holidays': 'ಮುಂಬರುವ ಬ್ಯಾಂಕ್ ರಜೆಗಳು',
  'set.dashHolidays': 'ಮುಖಪುಟ: ಮುಂಬರುವ ಬ್ಯಾಂಕ್ ರಜೆಗಳು',
  'visit.alarmLegend': 'ಅಲಾರಂ / ಯೋಜಿತ ಭೇಟಿ',
  'cal.addAlarm': 'ಈ ದಿನಾಂಕಕ್ಕೆ ಅಲಾರಂ',
  'cal.nothing': 'ಈ ದಿನ ಭೇಟಿ ಅಥವಾ ಅಲಾರಂ ಇಲ್ಲ. ಅಲಾರಂ ಹೊಂದಿಸಲು ಯಾವುದೇ ದಿನಾಂಕವನ್ನು ಒತ್ತಿ ಹಿಡಿಯಿರಿ.',
  'dash.setAlarm': 'ಅಲಾರಂ ಹೊಂದಿಸಿ',
  'dash.setAlarmSub': 'ಯಾವುದೇ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ – ಆಭರಣ ಇಡಲು/ತೆಗೆಯಲು, ಭೇಟಿ, ಏನಾದರೂ',

  // custom names / categories / types
  'item.nameHelp': 'ಯಾವುದೇ ಹೆಸರು ಟೈಪ್ ಮಾಡಿ – ಉದಾ: ಕಾಸಿನ ಸರ, ಬೆಳ್ಳಿ ದೀಪ, ಅಜ್ಜಿಯ ಉಂಗುರ, ಗಡಿಯಾರ',
  'item.newCategory': 'ಹೊಸ ವರ್ಗ',
  'item.newCategoryHint': 'ಉದಾ: ಹಿತ್ತಾಳೆ, ತಾಮ್ರ, ಪುರಾತನ, ಗಡಿಯಾರ, ದಾಖಲೆಗಳು',
  'item.newType': '+ ಹೊಸ ಬಗೆ (ನೀವೇ ಟೈಪ್ ಮಾಡಿ)',
  'item.newTypeHint': 'ಉದಾ: ವಂಕಿ, ಡಾಬು, ಬೆಳ್ಳಿ ತಟ್ಟೆ',
  'alerts.holidayWeekendsSub': 'ರಜೆ ಪಟ್ಟಿಯಲ್ಲಿ ತೋರಿಸಿ ಮತ್ತು ಮುಂಚೆ ಎಚ್ಚರಿಸಿ',
  'alerts.everySunday': 'ಪ್ರತಿ ಸಾಮಾನ್ಯ ಭಾನುವಾರವೂ',
  'alerts.everySundaySub': 'ಎಲ್ಲಾ ಭಾನುವಾರಗಳನ್ನು ಪಟ್ಟಿ ಮಾಡಿ ಎಚ್ಚರಿಸುತ್ತದೆ (ತಿಂಗಳಿಗೆ 4)',
  'fbk.title': 'Google Drive ಗೆ ಬ್ಯಾಕಪ್',
  'fbk.body': 'ಎಲ್ಲಾ ವಿವರ ಮತ್ತು ಫೋಟೋಗಳನ್ನು ನಿಮ್ಮ Google Drive‌ನ ಒಂದು ಫೈಲ್‌ನಲ್ಲಿ ಉಳಿಸುತ್ತದೆ. ಆ್ಯಪ್ ಅಳಿಸಿದರೆ ಅಥವಾ ಫೋನ್ ಬದಲಾದರೆ, GoldVault ಮತ್ತೆ ಇನ್‌ಸ್ಟಾಲ್ ಮಾಡಿ "ಬ್ಯಾಕಪ್ ಫೈಲ್‌ನಿಂದ ಮರುಸ್ಥಾಪಿಸಿ" ಒತ್ತಿ. ಪಾಸ್‌ವರ್ಡ್ ಬೇಡ.',
  'fbk.save': 'ಹೆಚ್ಚುವರಿ ಪ್ರತಿ ಉಳಿಸಿ (Drive ಆಯ್ಕೆಮಾಡಿ)',
  'fbk.share': 'ಬ್ಯಾಕಪ್ ಕಳುಹಿಸಿ (WhatsApp, Gmail, Drive…)',
  'fbk.restore': 'ಬ್ಯಾಕಪ್ ಫೈಲ್‌ನಿಂದ ಮರುಸ್ಥಾಪಿಸಿ',
  'fbk.saved': 'ಬ್ಯಾಕಪ್ ಉಳಿಸಲಾಗಿದೆ',
  'fbk.help': 'ಬ್ಯಾಕಪ್ ಫೈಲ್‌ಗಳು GoldVault ನಲ್ಲಿ ಮಾತ್ರ ತೆರೆಯುತ್ತವೆ. ಅವುಗಳನ್ನು ನಿಮ್ಮ ಸ್ವಂತ Google Drive ನಲ್ಲಿ ಇಡಿ.',
  'fbk.nudge': 'Google Drive ಗೆ ಬ್ಯಾಕಪ್ ಉಳಿಸಿ',
  'fbk.nudgeBody': 'ಆ್ಯಪ್ ಅಳಿಸಿದರೂ ನಿಮ್ಮ ಆಭರಣ ವಿವರ ಮತ್ತು ಫೋಟೋಗಳು ಸುರಕ್ಷಿತವಾಗಿರಲಿ. GoldVault → ಇನ್ನಷ್ಟು → ಸಿಂಕ್, ರಫ್ತು ಮತ್ತು ಬ್ಯಾಕಪ್ → ಸ್ವಯಂ ವಾರದ ಬ್ಯಾಕಪ್ ಆನ್ ಮಾಡಿ.',
  'backup.oldPass': 'ಈ ಬ್ಯಾಕಪ್ ಪಾಸ್‌ವರ್ಡ್‌ನೊಂದಿಗೆ ಮಾಡಲಾಗಿದೆ. ಆ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
  'backup.err.no_target': 'ಮೊದಲು ಬ್ಯಾಕಪ್ ಎಲ್ಲಿ ಉಳಿಸಬೇಕು ಆಯ್ಕೆಮಾಡಿ: "ಸ್ವಯಂ ವಾರದ ಬ್ಯಾಕಪ್ ಆನ್ ಮಾಡಿ" ಒತ್ತಿ',
  'backup.err.no_access': 'GoldVault ಗೆ ಬ್ಯಾಕಪ್ ಫೈಲ್‌ಗೆ ಬರೆಯಲು ಆಗುತ್ತಿಲ್ಲ. "ಬದಲಿಸಿ" ಒತ್ತಿ ಸ್ಥಳವನ್ನು ಮತ್ತೆ ಆಯ್ಕೆಮಾಡಿ.',
  'fbk.autoSub': 'ಪ್ರತಿ ವಾರ GoldVault ತಾನಾಗಿಯೇ Drive‌ನ ಬ್ಯಾಕಪ್ ಫೈಲ್ ನವೀಕರಿಸುತ್ತದೆ',
  'fbk.target': 'ಉಳಿಸುವ ಸ್ಥಳ: {name}',
  'fbk.inDrive': 'Google Drive',
  'fbk.setupHelp': 'ಕೆಳಗೆ ಒತ್ತಿ, ಮುಂದಿನ ಪರದೆಯಲ್ಲಿ "Drive" ಆಯ್ಕೆಮಾಡಿ Save ಒತ್ತಿ. ಇದನ್ನು ಒಮ್ಮೆ ಮಾತ್ರ ಕೇಳಲಾಗುತ್ತದೆ. ನಂತರ ಪ್ರತಿ ವಾರ ಬ್ಯಾಕಪ್ ತಾನಾಗಿಯೇ ಆಗುತ್ತದೆ.',
  'fbk.turnOn': 'ಸ್ವಯಂ ವಾರದ ಬ್ಯಾಕಪ್ ಆನ್ ಮಾಡಿ',
  'set.backupNudge': 'ಬ್ಯಾಕಪ್ ಜ್ಞಾಪನೆ',
  'set.backupNudgeSub': 'Google Drive ಗೆ ಬ್ಯಾಕಪ್ ಉಳಿಸಲು ವಾರಕ್ಕೊಮ್ಮೆ ನೆನಪಿಸಿ',
};
