// ಕನ್ನಡ strings. Missing keys fall back to English.
const Map<String, String> kn = {
  'nav.home': 'ಮುಖಪುಟ',
  'nav.items': 'ಆಭರಣಗಳು',
  'nav.places': 'ಲಾಕರ್‌ಗಳು',
  'nav.visits': 'ಭೇಟಿಗಳು',
  'nav.more': 'ಇನ್ನಷ್ಟು',

  'common.cancel': 'ರದ್ದುಮಾಡಿ',
  'common.change': 'ಬದಲಿಸಿ',
  'common.date': 'ದಿನಾಂಕ',
  'common.days': 'ದಿನಗಳು',
  'common.edit': 'ತಿದ್ದು',
  'common.invalidNumber': 'ಸರಿಯಾದ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
  'common.ok': 'ಸರಿ',
  'common.other': 'ಇತರೆ',
  'common.required': 'ಅಗತ್ಯವಿದೆ',
  'common.save': 'ಉಳಿಸಿ',
  'common.seeAll': 'ಎಲ್ಲಾ ನೋಡಿ',
  'common.set': 'ಹೊಂದಿಸಿ',
  'common.tapReveal': 'ನೋಡಲು ಒತ್ತಿ',
  'common.time': 'ಸಮಯ',

  'lock.create': '4 ಅಂಕಿಯ PIN ರಚಿಸಿ',
  'lock.confirm': 'PIN ಅನ್ನು ಮತ್ತೊಮ್ಮೆ ನಮೂದಿಸಿ',
  'lock.enter': 'ನಿಮ್ಮ PIN ನಮೂದಿಸಿ',
  'lock.mismatch': 'PIN ಹೊಂದಿಕೆಯಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  'lock.wrong': 'ತಪ್ಪು PIN',
  'lock.wait': 'ಹೆಚ್ಚು ಪ್ರಯತ್ನಗಳು. {s} ಸೆಕೆಂಡ್ ಕಾಯಿರಿ.',
  'lock.bioReason': 'GoldVault ತೆರೆಯಿರಿ',
  'lock.bioAsk': 'ಬೆರಳಚ್ಚು ಅಥವಾ ಮುಖದ ಮೂಲಕ ತೆರೆಯಬೇಕೇ?',
  'lock.bioYes': 'ಹೌದು, ಬೆರಳಚ್ಚು ಬಳಸಿ',
  'lock.bioNo': 'ಬೇಡ, PIN ಮಾತ್ರ',

  'dash.gold': 'ಒಟ್ಟು ಚಿನ್ನ',
  'dash.silver': 'ಒಟ್ಟು ಬೆಳ್ಳಿ',
  'dash.items': 'ಆಭರಣಗಳು',
  'dash.pcs': '{n} ತುಂಡು',
  'dash.value': 'ಅಂದಾಜು ಮೌಲ್ಯ',
  'dash.setRates': 'ದರ ಹೊಂದಿಸಿ',
  'dash.breakdown': 'ವಿಭಾಗವಾರು',
  'dash.byLocation': 'ಸ್ಥಳ',
  'dash.byOwner': 'ಮಾಲೀಕರು',
  'dash.byCategory': 'ಬಗೆ',
  'dash.empty': 'ಇನ್ನೂ ಯಾವುದೇ ಆಭರಣ ಇಲ್ಲ.',
  'dash.itemsN': '{n} ಆಭರಣ',
  'dash.goldShort': 'ಚಿನ್ನ',
  'dash.silverShort': 'ಬೆಳ್ಳಿ',
  'dash.noOwner': 'ಮಾಲೀಕರು ನಮೂದಿಸಿಲ್ಲ',
  'dash.upcoming': 'ಮುಂಬರುವ ಜ್ಞಾಪನೆಗಳು',
  'dash.noReminders': 'ಯಾವುದೂ ಬಾಕಿ ಇಲ್ಲ.',
  'dash.recent': 'ಇತ್ತೀಚಿನ ಚಲನೆಗಳು',
  'dash.noMoves': 'ಇನ್ನೂ ಯಾವುದೇ ಚಲನೆ ಇಲ್ಲ.',

  'rates.title': 'ಚಿನ್ನ ಮತ್ತು ಬೆಳ್ಳಿ ದರ',
  'rates.help': 'ಇಂದಿನ ಪ್ರತಿ ಗ್ರಾಂ ದರ ನಮೂದಿಸಿ. ಮೌಲ್ಯ ಅಂದಾಜಿಗೆ ಮಾತ್ರ; ಇಂಟರ್ನೆಟ್ ಬೇಕಿಲ್ಲ.',
  'rates.gold24': 'ಚಿನ್ನ 24K',
  'rates.silver': 'ಬೆಳ್ಳಿ',
  'rates.platinum': 'ಪ್ಲಾಟಿನಂ',
  'rates.notSet': 'ದರ ಹೊಂದಿಸಿಲ್ಲ – ಇಂದಿನ ದರ ನಮೂದಿಸಲು ಒತ್ತಿ',
  'rates.update': 'ನವೀಕರಿಸಿ',

  'where.title': 'ನನ್ನ ಆಭರಣ ಎಲ್ಲಿದೆ?',
  'where.hint': 'ಹೆಸರು, ಕ್ರಮ ಸಂಖ್ಯೆ, ಮಾಲೀಕರು ಅಥವಾ ಟ್ಯಾಗ್ ಟೈಪ್ ಮಾಡಿ',
  'where.prompt': 'ಕೆಲವು ಅಕ್ಷರ ಟೈಪ್ ಮಾಡಿ, ಉದಾ: "haram" ಅಥವಾ "GV-0012"',
  'where.since': '{date} ರಿಂದ',

  'inv.title': 'ಆಭರಣಗಳು',
  'inv.search': 'ಹೆಸರು, ಕ್ರಮ ಸಂಖ್ಯೆ, ಮಾಲೀಕರು, ಸ್ಥಳ, ಟ್ಯಾಗ್ ಹುಡುಕಿ',
  'inv.sort': 'ವಿಂಗಡಿಸಿ',
  'inv.filters': 'ಫಿಲ್ಟರ್‌ಗಳು',
  'inv.apply': 'ಅನ್ವಯಿಸಿ',
  'inv.clear': 'ತೆರವುಗೊಳಿಸಿ',
  'inv.empty': 'ಇನ್ನೂ ಯಾವುದೇ ಆಭರಣ ಇಲ್ಲ.\nಮೊದಲ ಆಭರಣ ಸೇರಿಸಲು "+ ಆಭರಣ ಸೇರಿಸಿ" ಒತ್ತಿ.',
  'inv.noMatch': 'ನಿಮ್ಮ ಹುಡುಕಾಟಕ್ಕೆ ಹೊಂದುವ ಆಭರಣ ಇಲ್ಲ.',
  'inv.outside': 'ಹೊರಗೆ (ಧರಿಸಿದೆ / ರಿಪೇರಿ / ಸಾಲ / ಅಡವು)',
  'inv.summary': '{n} ಆಭರಣಗಳು · ಒಟ್ಟು {w}',
  'sort.serial': 'ಕ್ರಮ ಸಂಖ್ಯೆ',
  'sort.name': 'ಹೆಸರು',
  'sort.weight': 'ತೂಕ',
  'sort.category': 'ಬಗೆ',
  'sort.location': 'ಸ್ಥಳ',
  'sort.date': 'ಸೇರಿಸಿದ ದಿನಾಂಕ',
  'sort.purchase': 'ಖರೀದಿ ದಿನಾಂಕ',

  'item.add': 'ಆಭರಣ ಸೇರಿಸಿ',
  'add.quick': 'ತ್ವರಿತ ಸೇರ್ಪಡೆ',
  'add.quickSub': 'ಹೆಸರು, ಬಗೆ, ತೂಕ, ಸ್ಥಳ ಮತ್ತು ಫೋಟೋ. ಉಳಿದದ್ದು ನಂತರ.',
  'add.purchase': 'ಹೊಸದಾಗಿ ಖರೀದಿಸಿದ್ದು',
  'add.purchaseSub': 'ಅಂಗಡಿ, ಬಿಲ್, ದರ, ತಯಾರಿಕಾ ಶುಲ್ಕ ಮತ್ತು GST ಸಹಿತ',
  'add.full': 'ಪೂರ್ಣ ವಿವರಗಳು',
  'add.fullSub': 'HUID ಮತ್ತು ಮಾಲೀಕತ್ವ ಸೇರಿ ಎಲ್ಲಾ ವಿವರಗಳು',
  'add.duplicate': 'ಇರುವ ಆಭರಣದ ನಕಲು',
  'add.duplicateSub': 'ಉದಾ: ಜೋಡಿ ಬಳೆಯ ಎರಡನೇ ಬಳೆ',
  'add.pickToCopy': 'ನಕಲು ಮಾಡಲು ಆಭರಣ ಆಯ್ಕೆಮಾಡಿ',
  'add.moreDetails': 'ಈಗಲೇ ಹೆಚ್ಚಿನ ವಿವರ ಸೇರಿಸಿ',
  'add.quickNote': 'ವಿವರಗಳನ್ನು ಯಾವಾಗ ಬೇಕಾದರೂ ನಂತರ ತುಂಬಬಹುದು.',

  'item.serial': 'ಕ್ರಮ ಸಂಖ್ಯೆ',
  'item.name': 'ಆಭರಣದ ಹೆಸರು',
  'item.type': 'ಆಭರಣದ ಬಗೆ',
  'item.category': 'ವರ್ಗ',
  'item.purity': 'ಶುದ್ಧತೆ',
  'item.customPurity': 'ಶುದ್ಧತೆ (ಟೈಪ್ ಮಾಡಿ)',
  'item.pieces': 'ತುಂಡುಗಳು',
  'item.weight': 'ತೂಕ',
  'item.weights': 'ತೂಕ',
  'item.gross': 'ಒಟ್ಟು ತೂಕ',
  'item.net': 'ನಿವ್ವಳ ತೂಕ',
  'item.stone': 'ಕಲ್ಲಿನ ತೂಕ',
  'item.photos': 'ಫೋಟೋಗಳು',
  'item.whereKept': 'ಎಲ್ಲಿ ಇಡಲಾಗಿದೆ?',
  'item.status': 'ಸ್ಥಿತಿ',
  'item.location': 'ಸ್ಥಳ',
  'item.statusNote': 'ಯಾರ ಬಳಿ / ಎಲ್ಲಿ?',
  'item.statusNoteHint': 'ಉದಾ: ಅಮ್ಮ ಧರಿಸಿದ್ದಾರೆ, ಲಲಿತಾ ಜ್ಯುವೆಲರ್ಸ್‌ನಲ್ಲಿ ರಿಪೇರಿ',
  'item.details': 'ವಿವರಗಳು',
  'item.description': 'ವಿವರಣೆ',
  'item.stones': 'ಕಲ್ಲು / ರತ್ನಗಳು',
  'item.huid': 'ಹಾಲ್‌ಮಾರ್ಕ್ / HUID ಸಂಖ್ಯೆ',
  'item.purchase': 'ಖರೀದಿ',
  'item.purchaseDate': 'ಖರೀದಿ ದಿನಾಂಕ',
  'item.shop': 'ಅಂಗಡಿಯ ಹೆಸರು',
  'item.billNo': 'ಬಿಲ್ ಸಂಖ್ಯೆ',
  'item.rate': 'ಪ್ರತಿ ಗ್ರಾಂ ದರ',
  'item.making': 'ತಯಾರಿಕಾ ಶುಲ್ಕ',
  'item.gst': 'GST',
  'item.total': 'ಒಟ್ಟು ಬೆಲೆ',
  'item.calc': 'ಒಟ್ಟು ಲೆಕ್ಕಹಾಕಿ',
  'item.calcNeed': 'ಮೊದಲು ದರ ಮತ್ತು ತೂಕ ನಮೂದಿಸಿ',
  'item.billPhoto': 'ಬಿಲ್ ಫೋಟೋ',
  'item.ownership': 'ಮಾಲೀಕತ್ವ ಮತ್ತು ಟಿಪ್ಪಣಿ',
  'item.owner': 'ಯಾರಿಗೆ ಸೇರಿದ್ದು',
  'item.occasion': 'ಸಂದರ್ಭ',
  'item.giftedBy': 'ಉಡುಗೊರೆ ನೀಡಿದವರು',
  'item.tags': 'ಟ್ಯಾಗ್‌ಗಳು',
  'item.tagsHint': 'ಅಲ್ಪವಿರಾಮದಿಂದ ಬೇರ್ಪಡಿಸಿ, ಉದಾ: ಮದುವೆ, ದಿನನಿತ್ಯ',
  'item.notes': 'ಟಿಪ್ಪಣಿ',
  'item.needLocation': 'ದಯವಿಟ್ಟು ಸ್ಥಳ ಆಯ್ಕೆಮಾಡಿ',
  'item.saved': '{serial} ಆಗಿ ಉಳಿಸಲಾಗಿದೆ',
  'item.edit': 'ಆಭರಣ ತಿದ್ದಿ',
  'item.move': 'ಸ್ಥಳ / ಸ್ಥಿತಿ ಬದಲಿಸಿ',
  'item.dispose': 'ಮಾರಾಟ / ಉಡುಗೊರೆ',
  'item.delete': 'ಅಳಿಸಿ (ತಪ್ಪು ನಮೂದು)',
  'item.deleteWarn': 'ಇದು ಆಭರಣ ಮತ್ತು ಅದರ ಸಂಪೂರ್ಣ ಇತಿಹಾಸವನ್ನು ಅಳಿಸುತ್ತದೆ. ಮಾರಾಟ, ವಿನಿಮಯ ಅಥವಾ ಉಡುಗೊರೆ ನೀಡಿದ್ದರೆ "ಮಾರಾಟ / ಉಡುಗೊರೆ" ಬಳಸಿ – ಇತಿಹಾಸ ಉಳಿಯುತ್ತದೆ.',
  'item.needsDetails': 'ತ್ವರಿತವಾಗಿ ಸೇರಿಸಲಾಗಿದೆ. ಉಳಿದ ವಿವರ ತುಂಬಲು ಒತ್ತಿ.',
  'item.history': 'ಚಲನೆಯ ಇತಿಹಾಸ',

  'status.in_locker': 'ಲಾಕರ್‌ನಲ್ಲಿ',
  'status.at_home': 'ಮನೆಯಲ್ಲಿ',
  'status.worn': 'ಧರಿಸಲಾಗಿದೆ',
  'status.repair': 'ರಿಪೇರಿಗೆ ಕೊಟ್ಟಿದೆ',
  'status.lent': 'ಸಾಲ ಕೊಟ್ಟಿದೆ',
  'status.pledged': 'ಅಡವು ಇಟ್ಟಿದೆ',
  'status.sold': 'ಮಾರಾಟ',
  'status.exchanged': 'ವಿನಿಮಯ',
  'status.gifted': 'ಉಡುಗೊರೆ ನೀಡಲಾಗಿದೆ',

  'move.title': 'ಆಭರಣ ಸ್ಥಳಾಂತರ',
  'move.disposeTitle': 'ಮಾರಾಟ, ವಿನಿಮಯ ಅಥವಾ ಉಡುಗೊರೆ',
  'move.disposeNote': 'ವಿವರ',
  'move.disposeHint': 'ಉದಾ: ಹೊಸ ಸರಕ್ಕೆ ವಿನಿಮಯ, ಪ್ರಿಯಾಗೆ ಉಡುಗೊರೆ',
  'move.disposeConfirm': '"{name}" ಇತಿಹಾಸದಲ್ಲಿ ಉಳಿಯುತ್ತದೆ, ಆದರೆ ಒಟ್ಟು ಲೆಕ್ಕದಲ್ಲಿ ಸೇರುವುದಿಲ್ಲ.',
  'move.visitTip': 'ಸಲಹೆ: ಬ್ಯಾಂಕ್ ಲಾಕರ್‌ನಲ್ಲಿ ಇಡುತ್ತಿದ್ದೀರಾ? ಭೇಟಿಯೂ ದಾಖಲಾಗಲು "ಭೇಟಿ ದಾಖಲಿಸಿ" ಬಳಸಿ.',
  'move.created': 'ಸೇರಿಸಲಾಗಿದೆ – {to}',
  'move.deposit': '{to} ನಲ್ಲಿ ಇಡಲಾಗಿದೆ',
  'move.withdraw': '{from} ನಿಂದ ತೆಗೆಯಲಾಗಿದೆ → {to}',
  'move.close': '{from} ನಿಂದ {to} ಗೆ (ಲಾಕರ್ ಮುಚ್ಚಲಾಗಿದೆ)',
  'move.moved': '{from} ನಿಂದ {to} ಗೆ ಸ್ಥಳಾಂತರ',
  'move.status': 'ಈಗ: {status}',

  'loc.title': 'ಲಾಕರ್ ಮತ್ತು ಸ್ಥಳಗಳು',
  'loc.addLocker': 'ಲಾಕರ್ ಸೇರಿಸಿ',
  'loc.editLocker': 'ಲಾಕರ್ ತಿದ್ದಿ',
  'loc.addPlace': 'ಸ್ಥಳ ಸೇರಿಸಿ (ಉದಾ: ಸಂಬಂಧಿಕರ ಮನೆ)',
  'loc.addSub': 'ಉಪ-ಸ್ಥಳ ಸೇರಿಸಿ',
  'loc.placeName': 'ಹೆಸರು, ಉದಾ: ದೇವರ ಕೋಣೆ ಕಪಾಟು',
  'loc.showClosed': 'ಮುಚ್ಚಿದ ಲಾಕರ್ ತೋರಿಸಿ',
  'loc.closed': 'ಮುಚ್ಚಲಾಗಿದೆ',
  'loc.closedOn': '{date} ರಂದು ಮುಚ್ಚಲಾಗಿದೆ',
  'loc.items': 'ಆಭರಣಗಳು',
  'loc.outside': 'ಮನೆ ಮತ್ತು ಲಾಕರ್‌ನ ಹೊರಗೆ (ಧರಿಸಿದೆ, ರಿಪೇರಿ, ಸಾಲ, ಅಡವು)',
  'loc.bankLocker': 'ಬ್ಯಾಂಕ್ ಲಾಕರ್',
  'loc.place': 'ಸ್ಥಳ',
  'loc.subs': 'ಉಪ-ಸ್ಥಳಗಳು',
  'loc.noSubs': 'ಇನ್ನೂ ಉಪ-ಸ್ಥಳಗಳಿಲ್ಲ.',
  'loc.itemsHere': 'ಇಲ್ಲಿರುವ ಆಭರಣಗಳು',
  'loc.noItems': 'ಈಗ ಇಲ್ಲಿ ಏನೂ ಇಲ್ಲ.',
  'loc.rename': 'ಹೆಸರು ಬದಲಿಸಿ',
  'loc.close': 'ಲಾಕರ್ ಮುಚ್ಚಿ',
  'loc.closeEmpty': 'ಈ ಲಾಕರ್ ಖಾಲಿಯಿದೆ. ಮುಚ್ಚಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಲಾಗುವುದು; ಇತಿಹಾಸ ಉಳಿಯುತ್ತದೆ.',
  'loc.closeMove': 'ಇನ್ನೂ {n} ಆಭರಣಗಳು ಒಳಗಿವೆ. ಮೊದಲು ಅವುಗಳನ್ನು ಎಲ್ಲಿಗೆ ಸ್ಥಳಾಂತರಿಸಬೇಕು ಎಂದು ಆಯ್ಕೆಮಾಡಿ.',
  'loc.moveTo': 'ಆಭರಣಗಳನ್ನು ಇಲ್ಲಿಗೆ ಸ್ಥಳಾಂತರಿಸಿ',
  'loc.closeConfirm': 'ಲಾಕರ್ ಮುಚ್ಚಿ',
  'loc.closedToast': 'ಲಾಕರ್ ಮುಚ್ಚಲಾಗಿದೆ. ಇತಿಹಾಸ ಉಳಿದಿದೆ.',
  'loc.reopen': 'ಮತ್ತೆ ತೆರೆಯಿರಿ',
  'loc.delete': 'ಅಳಿಸಿ',
  'loc.cantDelete': 'ಇಲ್ಲಿ ಆಭರಣ ಅಥವಾ ಇತಿಹಾಸ ಇರುವುದರಿಂದ ಅಳಿಸಲಾಗದು. ಬದಲಿಗೆ ಮುಚ್ಚಿ.',

  'locker.details': 'ಲಾಕರ್ ವಿವರಗಳು',
  'locker.bank': 'ಬ್ಯಾಂಕ್',
  'locker.otherBank': 'ಬ್ಯಾಂಕ್ ಹೆಸರು',
  'locker.name': 'ತೋರಿಸುವ ಹೆಸರು',
  'locker.nameHint': 'ಉದಾ: SBI ಜಯನಗರ ಲಾಕರ್',
  'locker.branch': 'ಶಾಖೆಯ ಹೆಸರು',
  'locker.address': 'ಶಾಖೆಯ ವಿಳಾಸ',
  'locker.number': 'ಲಾಕರ್ ಸಂಖ್ಯೆ',
  'locker.key': 'ಕೀ ಸಂಖ್ಯೆ',
  'locker.size': 'ಲಾಕರ್ ಗಾತ್ರ',
  'locker.opened': 'ಲಾಕರ್ ತೆರೆದ ದಿನಾಂಕ',
  'locker.people': 'ಹೊಂದಿರುವವರು ಮತ್ತು ನಾಮನಿರ್ದೇಶಿತರು',
  'locker.holders': 'ಹೊಂದಿರುವವರ ಹೆಸರು',
  'locker.joint': 'ಜಂಟಿ ಹೊಂದಿರುವವರು',
  'locker.nominee': 'ನಾಮನಿರ್ದೇಶಿತರು',
  'locker.rentSection': 'ಬಾಡಿಗೆ ಮತ್ತು ಸಂಪರ್ಕ',
  'locker.rent': 'ವಾರ್ಷಿಕ ಬಾಡಿಗೆ',
  'locker.rentDue': 'ಬಾಡಿಗೆ ಪಾವತಿ ದಿನಾಂಕ',
  'locker.contact': 'ಬ್ಯಾಂಕ್ ಸಂಪರ್ಕ ಸಂಖ್ಯೆ',
  'locker.colour': 'ಕ್ಯಾಲೆಂಡರ್ ಬಣ್ಣ',
  'locker.autoColour': 'ಬಣ್ಣವನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಆಯ್ಕೆಮಾಡಲಾಗುವುದು.',
  'locker.rentPaid': 'ಬಾಡಿಗೆ ಪಾವತಿಸಲಾಗಿದೆ',
  'locker.rentPaidBody': 'ಮುಂದಿನ ಪಾವತಿ ದಿನಾಂಕ {date} ಆಗಿರುತ್ತದೆ.',

  'visit.title': 'ಲಾಕರ್ ಭೇಟಿಗಳು',
  'visit.log': 'ಭೇಟಿ ದಾಖಲಿಸಿ',
  'visit.logNow': 'ದಾಖಲಿಸಿ',
  'visit.plan': 'ಭೇಟಿ ಯೋಜಿಸಿ',
  'visit.planned': '{date} ಕ್ಕೆ ಭೇಟಿ ಯೋಜಿಸಲಾಗಿದೆ',
  'visit.plannedLegend': 'ಯೋಜಿತ',
  'visit.month': 'ತಿಂಗಳು',
  'visit.week': 'ವಾರ',
  'visit.none': 'ಈ ದಿನ ಯಾವುದೇ ಭೇಟಿ ಇಲ್ಲ.',
  'visit.itemsMoved': '{n} ಚಲನೆ',
  'visit.whatMoved': 'ಈ ದಿನ ಏನೇನು ಚಲಿಸಿತು',
  'visit.locker': 'ಬ್ಯಾಂಕ್ ಲಾಕರ್',
  'visit.timeIn': 'ಒಳಗೆ ಹೋದ ಸಮಯ',
  'visit.timeOut': 'ಹೊರಬಂದ ಸಮಯ',
  'visit.timeOrder': 'ಹೊರಬಂದ ಸಮಯ ಒಳಗೆ ಹೋದ ಸಮಯದ ನಂತರ ಇರಬೇಕು',
  'visit.who': 'ಯಾರು ಭೇಟಿ ನೀಡಿದರು',
  'visit.whoHint': 'ಉದಾ: ಅಪ್ಪ, ಅಮ್ಮ',
  'visit.purpose': 'ಉದ್ದೇಶ',
  'visit.p.deposit': 'ಆಭರಣ ಇಡಲು',
  'visit.p.withdraw': 'ಆಭರಣ ತೆಗೆಯಲು',
  'visit.p.both': 'ಇಡಲು ಮತ್ತು ತೆಗೆಯಲು',
  'visit.p.check': 'ಪರಿಶೀಲನೆ',
  'visit.p.rent': 'ಬಾಡಿಗೆ / ಬ್ಯಾಂಕ್ ಕೆಲಸ',
  'visit.deposited': 'ಲಾಕರ್‌ನಲ್ಲಿ ಇಟ್ಟ ಆಭರಣಗಳು',
  'visit.withdrawn': 'ತೆಗೆದುಕೊಂಡ ಆಭರಣಗಳು',
  'visit.addDeposit': 'ಇಡುವ ಆಭರಣ ಆಯ್ಕೆಮಾಡಿ',
  'visit.addWithdraw': 'ತೆಗೆಯುವ ಆಭರಣ ಆಯ್ಕೆಮಾಡಿ',
  'visit.withdrawWhere': 'ತೆಗೆದ ಆಭರಣಗಳು ಈಗ…',
  'visit.pickLockerFirst': 'ಮೊದಲು ಲಾಕರ್ ಆಯ್ಕೆಮಾಡಿ',
  'visit.saved': 'ಭೇಟಿ ಉಳಿಸಲಾಗಿದೆ · {n} ಆಭರಣ ನವೀಕರಿಸಲಾಗಿದೆ',
  'visit.edit': 'ಭೇಟಿ ತಿದ್ದಿ',
  'visit.editNote': 'ದಿನಾಂಕ, ಸಮಯ ಮತ್ತು ಟಿಪ್ಪಣಿ ಬದಲಿಸಬಹುದು. ಈ ಭೇಟಿಯಲ್ಲಿ ಚಲಿಸಿದ ಆಭರಣಗಳು ಹಾಗೆಯೇ ಉಳಿಯುತ್ತವೆ.',
  'visit.detail': 'ಭೇಟಿ',
  'visit.delete': 'ಭೇಟಿ ಅಳಿಸಿ',
  'visit.noItems': 'ಯಾವುದೂ ಇಲ್ಲ',
  'visit.recent': 'ಇತ್ತೀಚಿನ ಭೇಟಿಗಳು',

  'rem.title': 'ಜ್ಞಾಪನೆಗಳು',
  'rem.add': 'ಜ್ಞಾಪನೆ ಸೇರಿಸಿ',
  'rem.rent': 'ಲಾಕರ್ ಬಾಡಿಗೆ ಬಾಕಿ',
  'rem.notReturned': 'ಇನ್ನೂ ಹಿಂತಿರುಗಿಲ್ಲ',
  'rem.planned': 'ಯೋಜಿತ ಭೇಟಿ',
  'rem.custom': 'ಜ್ಞಾಪನೆ',
  'rem.overdue': 'ಅವಧಿ ಮೀರಿದೆ',
  'rem.outSince': '{date} ರಿಂದ ಹೊರಗಿದೆ',
  'rem.done': 'ಮುಗಿದಿದೆ',
  'rem.rules': 'ಜ್ಞಾಪನೆ ನಿಯಮಗಳು',
  'rem.rulesBody': 'ಆಭರಣ {days} ದಿನ ಲಾಕರ್/ಮನೆಯಿಂದ ಹೊರಗಿದ್ದರೆ ಮತ್ತು ಲಾಕರ್ ಬಾಡಿಗೆಗೆ {lead} ದಿನ ಮುಂಚೆ ನೆನಪಿಸಲಾಗುವುದು.',
  'rem.notReturnedDays': 'ಹಿಂತಿರುಗದಿದ್ದರೆ ನೆನಪಿಸುವ ಅವಧಿ',
  'rem.rentLead': 'ಬಾಡಿಗೆಗೆ ಎಷ್ಟು ಮುಂಚೆ',
  'rem.what': 'ಏನನ್ನು ನೆನಪಿಸಬೇಕು',
  'rem.whatHint': 'ಉದಾ: ರಿಪೇರಿಯಿಂದ ಸರ ತರಬೇಕು',
  'rem.lockerOptional': 'ಲಾಕರ್ (ಯೋಜಿತ ಭೇಟಿಗೆ)',

  'picker.none': 'ಹೊಂದುವ ಆಭರಣ ಇಲ್ಲ.',
  'picker.done': 'ಆಯ್ತು ({n} ಆಯ್ಕೆ)',
  'photo.camera': 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
  'photo.gallery': 'ಗ್ಯಾಲರಿಯಿಂದ ಆಯ್ಕೆಮಾಡಿ',
  'photo.add': 'ಫೋಟೋ ಸೇರಿಸಿ',
  'photo.count': '{max} ರಲ್ಲಿ {n} ಫೋಟೋ · ಆಯ್ಕೆಗಳಿಗೆ ಫೋಟೋವನ್ನು ಒತ್ತಿ ಹಿಡಿಯಿರಿ',
  'photo.countNone': 'ಇನ್ನೂ ಫೋಟೋ ಇಲ್ಲ · ಪ್ರತಿ ಆಭರಣಕ್ಕೆ {max} ವರೆಗೆ',
  'photo.attachBill': 'ಬಿಲ್ ಫೋಟೋ ಲಗತ್ತಿಸಿ',
  'photo.added': '{n} ಫೋಟೋ ಲಗತ್ತಿಸಲಾಗಿದೆ',
  'photo.full': 'ಈಗಾಗಲೇ {max} ಫೋಟೋಗಳಿವೆ. ಹೊಸದನ್ನು ಸೇರಿಸಲು ಒಂದನ್ನು ತೆಗೆಯಿರಿ.',
  'photo.makeMain': 'ಮುಖ್ಯ ಫೋಟೋ ಮಾಡಿ',
  'photo.share': 'ಫೋಟೋ ಹಂಚಿಕೊಳ್ಳಿ',
  'photo.replace': 'ಬದಲಿಸಿ',
  'photo.remove': 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
  'photo.removeBody': 'ಈ ಫೋಟೋವನ್ನು GoldVault ನಿಂದ ಅಳಿಸಲಾಗುವುದು.',

  'set.title': 'ಇನ್ನಷ್ಟು',
  'set.language': 'ಭಾಷೆ',
  'set.general': 'ಸಾಮಾನ್ಯ',
  'set.cloud': 'Google Sheets, ರಫ್ತು ಮತ್ತು ಬ್ಯಾಕಪ್',
  'set.security': 'ಭದ್ರತೆ',
  'set.changePin': 'PIN ಬದಲಿಸಿ',
  'set.currentPin': 'ಈಗಿನ PIN',
  'set.newPin': 'ಹೊಸ PIN',
  'set.confirmPin': 'ಹೊಸ PIN ಮತ್ತೊಮ್ಮೆ',
  'set.pinChanged': 'PIN ಬದಲಾಯಿಸಲಾಗಿದೆ',
  'set.biometric': 'ಬೆರಳಚ್ಚು / ಮುಖ ಗುರುತು',
  'set.biometricSub': 'PIN ಟೈಪ್ ಮಾಡದೆ ತೆರೆಯಿರಿ',
  'set.biometricNA': 'ಈ ಫೋನ್‌ನಲ್ಲಿ ಲಭ್ಯವಿಲ್ಲ',
  'set.blockAll': 'ಎಲ್ಲೆಡೆ ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ತಡೆಯಿರಿ',
  'set.blockAllSub': 'ಆಫ್ ಇದ್ದರೆ, ಮೌಲ್ಯ ಮತ್ತು ಲಾಕರ್ ವಿವರಗಳಿರುವ ಪರದೆಗಳಲ್ಲಿ ಮಾತ್ರ ತಡೆಯಲಾಗುತ್ತದೆ',
  'set.lockNow': 'ಈಗ ಲಾಕ್ ಮಾಡಿ',
  'set.autoLock': 'ಹಿನ್ನೆಲೆಯಲ್ಲಿ 1 ನಿಮಿಷದ ನಂತರ ಸ್ವಯಂ ಲಾಕ್ ಆಗುತ್ತದೆ',
  'set.about': 'ಆ್ಯಪ್ ಬಗ್ಗೆ',
  'set.aboutBody': 'ನಿಮ್ಮ ಮಾಹಿತಿ ಈ ಫೋನ್‌ನಲ್ಲೇ ಗೂಢಲಿಪಿಯ ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ಇರುತ್ತದೆ ಮತ್ತು ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದೆಯೂ ಸಂಪೂರ್ಣವಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ. Google Sheets ಸಿಂಕ್ ಅಥವಾ Google Drive ಬ್ಯಾಕಪ್‌ಗೆ ಮಾತ್ರ ಇಂಟರ್ನೆಟ್ ಬಳಸಲಾಗುತ್ತದೆ.',

  'cloud.title': 'ಸಿಂಕ್, ರಫ್ತು ಮತ್ತು ಬ್ಯಾಕಪ್',
  'cloud.subtitle': 'Google Sheets, Excel, PDF ಮತ್ತು Drive ಬ್ಯಾಕಪ್',
  'cloud.offlineNote': 'ಎಲ್ಲವೂ ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ. ಈ ಸೌಲಭ್ಯಗಳು ನಡೆಯುವಾಗ ಮಾತ್ರ ಇಂಟರ್ನೆಟ್ ಬೇಕು.',
  'cloud.account': 'Google ಖಾತೆ',
  'cloud.signedOut': 'ಸೈನ್ ಇನ್ ಆಗಿಲ್ಲ',
  'cloud.signIn': 'Google ಮೂಲಕ ಸೈನ್ ಇನ್',
  'cloud.signOut': 'ಸೈನ್ ಔಟ್',
  'cloud.signOutBody': 'ಮತ್ತೆ ಸೈನ್ ಇನ್ ಆಗುವವರೆಗೆ ಸ್ವಯಂ ಸಿಂಕ್ ಮತ್ತು ಬ್ಯಾಕಪ್ ನಿಲ್ಲುತ್ತದೆ. ಫೋನ್‌ನಲ್ಲಿರುವ ಮಾಹಿತಿಗೆ ಏನೂ ಆಗುವುದಿಲ್ಲ.',
  'cloud.notConfigured': 'ಈ ಆವೃತ್ತಿಯಲ್ಲಿ Google ಸೈನ್-ಇನ್ ಹೊಂದಿಸಿಲ್ಲ. ಆ್ಯಪ್ ನಿರ್ಮಿಸಿದವರಿಗೆ Google client ID ಸೇರಿಸಲು ಹೇಳಿ (README ನೋಡಿ).',
  'cloud.cancelled': 'ಸೈನ್ ಇನ್ ರದ್ದಾಯಿತು',
  'cloud.signInFailed': 'Google ಸೈನ್ ಇನ್ ವಿಫಲವಾಯಿತು',
  'cloud.offline': 'ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕವಿಲ್ಲ. ಆನ್‌ಲೈನ್ ಆದಾಗ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  'cloud.error': 'ಏನೋ ತಪ್ಪಾಗಿದೆ',

  'sheet.title': 'Google Sheets',
  'sheet.body': 'ಆ್ಯಪ್‌ನಲ್ಲಿರುವುದೇ ಮುಖ್ಯ ಪ್ರತಿ. ನಿಮ್ಮ ಮಾಹಿತಿ "GoldVault Inventory" ಎಂಬ Google Sheet‌ಗೆ (ಮೊದಲ ಸಿಂಕ್‌ನಲ್ಲಿ ರಚನೆ) ಒಂದು ದಿಕ್ಕಿನಲ್ಲಿ ನಕಲಾಗುತ್ತದೆ; ಪ್ರತಿ ಲಾಕರ್‌ಗೆ ಪ್ರತ್ಯೇಕ ಟ್ಯಾಬ್.',
  'sheet.never': 'ಇನ್ನೂ ಸಿಂಕ್ ಆಗಿಲ್ಲ',
  'sheet.last': 'ಕೊನೆಯ ಸಿಂಕ್ {date}',
  'sheet.pending': 'ಸಿಂಕ್‌ಗೆ ಬದಲಾವಣೆಗಳು ಬಾಕಿ ಇವೆ',
  'sheet.auto': 'ಆನ್‌ಲೈನ್ ಆದಾಗ ಸ್ವಯಂ ಸಿಂಕ್',
  'sheet.autoSub': 'ಬದಲಾವಣೆಗಳ ನಂತರ ಹಿನ್ನೆಲೆಯಲ್ಲಿ ಸಿಂಕ್ ಆಗುತ್ತದೆ',
  'sheet.syncNow': 'ಈಗ ಸಿಂಕ್ ಮಾಡಿ',
  'sheet.synced': 'Google Sheet ನವೀಕರಿಸಲಾಗಿದೆ',
  'sheet.share': 'Sheet ಹಂಚಿಕೊಳ್ಳಿ',
  'sheet.email': 'ಇಮೇಲ್ ವಿಳಾಸ',
  'sheet.view': 'ನೋಡಲು ಮಾತ್ರ',
  'sheet.edit': 'ತಿದ್ದಬಹುದು',
  'sheet.shareBtn': 'ಹಂಚಿಕೊಳ್ಳಿ',
  'sheet.sharedWith': '{email} ಜೊತೆ ಹಂಚಿಕೊಳ್ಳಲಾಗಿದೆ',
  'sheet.copyLink': 'Sheet ಲಿಂಕ್ ನಕಲಿಸಿ',
  'sheet.copied': 'ಲಿಂಕ್ ನಕಲಿಸಲಾಗಿದೆ',

  'export.title': 'ರಫ್ತು',
  'export.body': 'Excel ಫೈಲ್ ಅಥವಾ PDF ವರದಿ ರಚಿಸಿ WhatsApp, ಇಮೇಲ್ ಮೂಲಕ ಹಂಚಿಕೊಳ್ಳಿ. ಇಂಟರ್ನೆಟ್ ಬೇಕಿಲ್ಲ.',
  'export.excel': 'Excel (.xlsx) ಗೆ ರಫ್ತು',
  'export.pdf': 'PDF ವರದಿ',

  'backup.title': 'Google Drive ಬ್ಯಾಕಪ್',
  'backup.body': 'ಸಂಪೂರ್ಣ ಡೇಟಾಬೇಸ್ ಮತ್ತು ಎಲ್ಲಾ ಫೋಟೋಗಳ ಗೂಢಲಿಪಿ ಬ್ಯಾಕಪ್ ನಿಮ್ಮ Google Drive‌ನ "GoldVault Backups" ಫೋಲ್ಡರ್‌ಗೆ. ಕೊನೆಯ 8 ಬ್ಯಾಕಪ್‌ಗಳನ್ನು ಉಳಿಸಲಾಗುತ್ತದೆ.',
  'backup.never': 'ಇನ್ನೂ ಬ್ಯಾಕಪ್ ಆಗಿಲ್ಲ',
  'backup.last': 'ಕೊನೆಯ ಬ್ಯಾಕಪ್: {date}',
  'backup.passSet': 'ಬ್ಯಾಕಪ್ ಪಾಸ್‌ವರ್ಡ್ ಹೊಂದಿಸಲಾಗಿದೆ',
  'backup.passNotSet': 'ಬ್ಯಾಕಪ್ ಪಾಸ್‌ವರ್ಡ್ ಹೊಂದಿಸಿಲ್ಲ',
  'backup.passHelp': 'ಹೊಸ ಫೋನ್‌ನಲ್ಲಿ ಮರುಸ್ಥಾಪಿಸಲು ಬೇಕು',
  'backup.passTitle': 'ಬ್ಯಾಕಪ್ ಪಾಸ್‌ವರ್ಡ್',
  'backup.passWarn': 'ಈ ಪಾಸ್‌ವರ್ಡ್ ಬರೆದು ಸುರಕ್ಷಿತವಾಗಿಡಿ. ಇದಿಲ್ಲದೆ ಬ್ಯಾಕಪ್ ತೆರೆಯಲು ಯಾರಿಗೂ ಸಾಧ್ಯವಿಲ್ಲ.',
  'backup.pass': 'ಪಾಸ್‌ವರ್ಡ್',
  'backup.passAgain': 'ಪಾಸ್‌ವರ್ಡ್ ಮತ್ತೊಮ್ಮೆ',
  'backup.passShort': 'ಕನಿಷ್ಠ 8 ಅಕ್ಷರ ಬಳಸಿ',
  'backup.weekly': 'ಸ್ವಯಂ ವಾರದ ಬ್ಯಾಕಪ್',
  'backup.day': 'ದಿನ',
  'backup.time': 'ಸಮಯ',
  'backup.wifiOnly': 'Wi-Fi ಇದ್ದಾಗ ಮಾತ್ರ',
  'backup.next': 'ಮುಂದಿನ ಬ್ಯಾಕಪ್ ಸುಮಾರು {date}. ಫೋನ್ ಆಫ್‌ಲೈನ್ ಇದ್ದರೆ, ಸಂಪರ್ಕ ಸಿಕ್ಕ ತಕ್ಷಣ ನಡೆಯುತ್ತದೆ.',
  'backup.now': 'ಈಗ ಬ್ಯಾಕಪ್ ಮಾಡಿ',
  'backup.restore': 'Drive ನಿಂದ ಮರುಸ್ಥಾಪಿಸಿ',
  'backup.keepNote': 'ಮರುಸ್ಥಾಪನೆ ಈ ಫೋನ್‌ನ ಎಲ್ಲಾ ಮಾಹಿತಿಯನ್ನು ಬ್ಯಾಕಪ್‌ನಿಂದ ಬದಲಿಸುತ್ತದೆ.',
  'backup.none': 'Google Drive ನಲ್ಲಿ ಬ್ಯಾಕಪ್ ಸಿಗಲಿಲ್ಲ',
  'backup.choose': 'ಬ್ಯಾಕಪ್ ಆಯ್ಕೆಮಾಡಿ',
  'backup.enterPass': 'ಬ್ಯಾಕಪ್ ಪಾಸ್‌ವರ್ಡ್',
  'backup.restoreWarn': 'ಈ ಫೋನ್‌ನ ಎಲ್ಲಾ ಆಭರಣ, ಲಾಕರ್, ಭೇಟಿ ಮತ್ತು ಫೋಟೋಗಳನ್ನು ಬ್ಯಾಕಪ್‌ನಿಂದ ಬದಲಿಸಲಾಗುವುದು. ಮುಂದುವರಿಯಬೇಕೇ?',
  'backup.restoreBtn': 'ಮರುಸ್ಥಾಪಿಸಿ',
  'backup.restored': 'ಮರುಸ್ಥಾಪಿಸಲಾಗಿದೆ · {n} ಆಭರಣಗಳು',
  'backup.err.no_passphrase': 'ಮೊದಲು ಬ್ಯಾಕಪ್ ಪಾಸ್‌ವರ್ಡ್ ಹೊಂದಿಸಿ',
  'backup.err.not_signed_in': 'ಮೊದಲು Google ಮೂಲಕ ಸೈನ್ ಇನ್ ಮಾಡಿ',
  'backup.err.wrong_passphrase': 'ತಪ್ಪು ಬ್ಯಾಕಪ್ ಪಾಸ್‌ವರ್ಡ್',
  'backup.err.bad_file': 'ಇದು ಮಾನ್ಯ GoldVault ಬ್ಯಾಕಪ್ ಅಲ್ಲ',

  'notif.rent': 'ಲಾಕರ್ ಬಾಡಿಗೆ ಬಾಕಿ: {name}',
  'notif.rentBody': '{date} ರಂದು ಪಾವತಿಸಬೇಕು {amount}',
  'notif.notReturned': 'ಆಭರಣ ಇನ್ನೂ ಹಿಂತಿರುಗಿಲ್ಲ',
  'notif.notReturnedBody': '{name} {date} ರಿಂದ ಹೊರಗಿದೆ',
  'notif.planned': 'ಯೋಜಿತ ಲಾಕರ್ ಭೇಟಿ: {name}',
  'notif.plannedBody': '{date} ರಂದು',
  'notif.backupDone': 'GoldVault ಬ್ಯಾಕಪ್ ಪೂರ್ಣಗೊಂಡಿದೆ',
  'notif.backupFailed': 'GoldVault ಬ್ಯಾಕಪ್‌ಗೆ ಗಮನ ಬೇಕು',

  'opt.SBI': 'SBI',
  'opt.HDFC': 'HDFC',
  'opt.ICICI': 'ICICI',
  'opt.Axis': 'ಆಕ್ಸಿಸ್',
  'opt.Canara': 'ಕೆನರಾ',
  'opt.Union Bank': 'ಯೂನಿಯನ್ ಬ್ಯಾಂಕ್',
  'opt.Bank of Baroda': 'ಬ್ಯಾಂಕ್ ಆಫ್ ಬರೋಡಾ',
  'opt.Karnataka Bank': 'ಕರ್ಣಾಟಕ ಬ್ಯಾಂಕ್',
  'opt.Other': 'ಇತರೆ',
  'opt.Small': 'ಸಣ್ಣ',
  'opt.Medium': 'ಮಧ್ಯಮ',
  'opt.Large': 'ದೊಡ್ಡ',
  'opt.Extra Large': 'ಅತಿ ದೊಡ್ಡ',
  'opt.Gold': 'ಚಿನ್ನ',
  'opt.Silver': 'ಬೆಳ್ಳಿ',
  'opt.Diamond': 'ವಜ್ರ',
  'opt.Platinum': 'ಪ್ಲಾಟಿನಂ',
  'opt.Necklace': 'ನೆಕ್ಲೇಸ್',
  'opt.Long chain (Haram)': 'ಉದ್ದ ಸರ (ಹಾರ)',
  'opt.Chain': 'ಸರ',
  'opt.Mangalsutra': 'ಮಾಂಗಲ್ಯ ಸರ',
  'opt.Bangle': 'ಬಳೆ',
  'opt.Bracelet': 'ಕಡಗ',
  'opt.Ring': 'ಉಂಗುರ',
  'opt.Earrings': 'ಕಿವಿಯೋಲೆ',
  'opt.Jhumka': 'ಜುಮುಕಿ',
  'opt.Nose pin': 'ಮೂಗುತಿ',
  'opt.Anklet': 'ಕಾಲ್ಗೆಜ್ಜೆ',
  'opt.Toe ring': 'ಕಾಲುಂಗುರ',
  'opt.Waist belt (Vaddanam)': 'ಒಡ್ಯಾಣ',
  'opt.Pendant': 'ಪದಕ',
  'opt.Coin': 'ನಾಣ್ಯ',
  'opt.Bar': 'ಬಿಸ್ಕತ್ / ಬಾರ್',
  'opt.Idol': 'ವಿಗ್ರಹ',
  'opt.Utensil': 'ಪಾತ್ರೆ',
  'opt.Pooja item': 'ಪೂಜಾ ಸಾಮಗ್ರಿ',
  'opt.Watch': 'ಗಡಿಯಾರ',
};
