// English strings. `{name}` placeholders are filled by S.t().
const Map<String, String> en = {
  // navigation
  'nav.home': 'Home',
  'nav.items': 'Ornaments',
  'nav.places': 'Lockers',
  'nav.visits': 'Visits',
  'nav.more': 'More',

  // common
  'common.cancel': 'Cancel',
  'common.change': 'Change',
  'common.date': 'Date',
  'common.days': 'days',
  'common.edit': 'Edit',
  'common.invalidNumber': 'Enter a valid number',
  'common.ok': 'OK',
  'common.other': 'Other',
  'common.required': 'Required',
  'common.save': 'Save',
  'common.seeAll': 'See all',
  'common.set': 'Set',
  'common.tapReveal': 'tap to show',
  'common.time': 'Time',

  // lock
  'lock.create': 'Create a 4-digit PIN',
  'lock.confirm': 'Enter the PIN again',
  'lock.enter': 'Enter your PIN',
  'lock.mismatch': 'PINs did not match. Try again.',
  'lock.wrong': 'Wrong PIN',
  'lock.wait': 'Too many tries. Wait {s} seconds.',
  'lock.bioReason': 'Unlock GoldVault',
  'lock.bioAsk': 'Use fingerprint or face to unlock?',
  'lock.bioYes': 'Yes, use fingerprint',
  'lock.bioNo': 'No, PIN only',

  // dashboard
  'dash.gold': 'Total gold',
  'dash.silver': 'Total silver',
  'dash.items': 'Ornaments',
  'dash.pcs': '{n} pcs',
  'dash.value': 'Estimated value',
  'dash.setRates': 'Set rates',
  'dash.breakdown': 'Breakdown',
  'dash.byLocation': 'Location',
  'dash.byOwner': 'Owner',
  'dash.byCategory': 'Type',
  'dash.empty': 'No ornaments yet.',
  'dash.itemsN': '{n} items',
  'dash.goldShort': 'Gold',
  'dash.silverShort': 'Silver',
  'dash.noOwner': 'Owner not set',
  'dash.upcoming': 'Upcoming reminders',
  'dash.noReminders': 'Nothing due. All good!',
  'dash.recent': 'Recent movements',
  'dash.noMoves': 'No movements yet.',

  // rates
  'rates.title': 'Gold & silver rates',
  'rates.help': 'Enter today\'s rate per gram. Used only to estimate value; works offline.',
  'rates.gold24': 'Gold 24K',
  'rates.silver': 'Silver',
  'rates.platinum': 'Platinum',
  'rates.notSet': 'Rates not set – tap to enter today\'s rate',
  'rates.update': 'Update',

  // where is
  'where.title': 'Where is my ornament?',
  'where.hint': 'Type name, serial, owner or tag',
  'where.prompt': 'Type a few letters, e.g. "haram" or "GV-0012"',
  'where.since': 'Since {date}',

  // inventory
  'inv.title': 'Ornaments',
  'inv.search': 'Search name, serial, owner, place, tag',
  'inv.sort': 'Sort',
  'inv.filters': 'Filters',
  'inv.apply': 'Apply',
  'inv.clear': 'Clear',
  'inv.empty': 'No ornaments yet.\nTap "+ Add Ornament" to add your first one.',
  'inv.noMatch': 'Nothing matches your search or filters.',
  'inv.outside': 'Out (worn / repair / lent / pledged)',
  'inv.summary': '{n} ornaments · {w} total',
  'sort.serial': 'Serial number',
  'sort.name': 'Name',
  'sort.weight': 'Weight',
  'sort.category': 'Category',
  'sort.location': 'Location',
  'sort.date': 'Date added',
  'sort.purchase': 'Purchase date',

  // add flows
  'item.add': 'Add Ornament',
  'add.quick': 'Quick add',
  'add.quickSub': 'Name, type, weight, place and photo. Fill the rest later.',
  'add.purchase': 'Newly purchased',
  'add.purchaseSub': 'With shop, bill, rate, making charges and GST',
  'add.full': 'Full details',
  'add.fullSub': 'Every field, including HUID and ownership',
  'add.duplicate': 'Copy an existing ornament',
  'add.duplicateSub': 'E.g. the second bangle of a set',
  'add.pickToCopy': 'Choose ornament to copy',
  'add.moreDetails': 'Add more details now',
  'add.quickNote': 'You can complete the details any time later.',

  // item
  'item.serial': 'Serial no.',
  'item.name': 'Ornament name',
  'item.type': 'Ornament type',
  'item.category': 'Category',
  'item.purity': 'Purity',
  'item.customPurity': 'Purity (type it)',
  'item.pieces': 'Pieces',
  'item.weight': 'Weight',
  'item.weights': 'Weight',
  'item.gross': 'Gross wt',
  'item.net': 'Net wt',
  'item.stone': 'Stone wt',
  'item.photos': 'Photos',
  'item.whereKept': 'Where is it kept?',
  'item.status': 'Status',
  'item.location': 'Location',
  'item.statusNote': 'With whom / where?',
  'item.statusNoteHint': 'E.g. worn by Amma, repair at Lalitha Jewellers',
  'item.details': 'Details',
  'item.description': 'Description',
  'item.stones': 'Stones / gems',
  'item.huid': 'Hallmark / HUID number',
  'item.purchase': 'Purchase',
  'item.purchaseDate': 'Purchase date',
  'item.shop': 'Shop name',
  'item.billNo': 'Bill number',
  'item.rate': 'Rate per gram',
  'item.making': 'Making charges',
  'item.gst': 'GST',
  'item.total': 'Total price',
  'item.calc': 'Calculate total',
  'item.calcNeed': 'Enter rate and weight first',
  'item.billPhoto': 'Bill photo',
  'item.ownership': 'Ownership & notes',
  'item.owner': 'Belongs to',
  'item.occasion': 'Occasion',
  'item.giftedBy': 'Gifted by',
  'item.tags': 'Tags',
  'item.tagsHint': 'Comma separated, e.g. wedding, daily wear',
  'item.notes': 'Notes',
  'item.needLocation': 'Please choose the location',
  'item.saved': 'Saved as {serial}',
  'item.edit': 'Edit ornament',
  'item.move': 'Move / status',
  'item.dispose': 'Sold / gifted',
  'item.delete': 'Delete (wrong entry)',
  'item.deleteWarn': 'This removes the ornament and its whole history. If it was sold, exchanged or gifted, use "Sold / gifted" instead so the history stays.',
  'item.needsDetails': 'Added with quick add. Tap to fill in the remaining details.',
  'item.history': 'Movement history',

  // statuses
  'status.in_locker': 'In locker',
  'status.at_home': 'At home',
  'status.worn': 'Being worn',
  'status.repair': 'Given for repair',
  'status.lent': 'Lent',
  'status.pledged': 'Pledged',
  'status.sold': 'Sold',
  'status.exchanged': 'Exchanged',
  'status.gifted': 'Gifted',

  // movements
  'move.title': 'Move ornament',
  'move.disposeTitle': 'Sold, exchanged or gifted',
  'move.disposeNote': 'Details',
  'move.disposeHint': 'E.g. exchanged at GRT for new chain, gifted to Priya',
  'move.disposeConfirm': '"{name}" will stay in history but will no longer be counted in totals.',
  'move.visitTip': 'Tip: putting items in a bank locker? Use "Log visit" so the visit is recorded too.',
  'move.created': 'Added – {to}',
  'move.deposit': 'Kept in {to}',
  'move.withdraw': 'Taken out of {from} → {to}',
  'move.close': 'Moved from {from} to {to} (locker closed)',
  'move.moved': 'Moved from {from} to {to}',
  'move.status': 'Now: {status}',

  // locations
  'loc.title': 'Lockers & places',
  'loc.addLocker': 'Add Locker',
  'loc.editLocker': 'Edit locker',
  'loc.addPlace': 'Add a place (e.g. relative\'s house)',
  'loc.addSub': 'Add sub-location',
  'loc.placeName': 'Name, e.g. Pooja room cupboard',
  'loc.showClosed': 'Show closed lockers',
  'loc.closed': 'closed',
  'loc.closedOn': 'Closed on {date}',
  'loc.items': 'Items',
  'loc.outside': 'Out of home & lockers (worn, repair, lent, pledged)',
  'loc.bankLocker': 'Bank locker',
  'loc.place': 'Place',
  'loc.subs': 'Sub-locations',
  'loc.noSubs': 'No sub-locations yet.',
  'loc.itemsHere': 'Ornaments here',
  'loc.noItems': 'Nothing kept here right now.',
  'loc.rename': 'Rename',
  'loc.close': 'Close locker',
  'loc.closeEmpty': 'This locker is empty. It will be marked closed; its history is kept.',
  'loc.closeMove': '{n} ornaments are still inside. Choose where to move them first.',
  'loc.moveTo': 'Move items to',
  'loc.closeConfirm': 'Close locker',
  'loc.closedToast': 'Locker closed. History is kept.',
  'loc.reopen': 'Reopen',
  'loc.delete': 'Delete',
  'loc.cantDelete': 'This place has items or history, so it can\'t be deleted. Close it instead.',

  // locker fields
  'locker.details': 'Locker details',
  'locker.bank': 'Bank',
  'locker.otherBank': 'Bank name',
  'locker.name': 'Display name',
  'locker.nameHint': 'E.g. SBI Jayanagar locker',
  'locker.branch': 'Branch name',
  'locker.address': 'Branch address',
  'locker.number': 'Locker number',
  'locker.key': 'Key number',
  'locker.size': 'Locker size',
  'locker.opened': 'Locker opened on',
  'locker.people': 'Holders & nominee',
  'locker.holders': 'Holder name(s)',
  'locker.joint': 'Joint holder(s)',
  'locker.nominee': 'Nominee',
  'locker.rentSection': 'Rent & contact',
  'locker.rent': 'Annual rent',
  'locker.rentDue': 'Rent due date',
  'locker.contact': 'Bank contact number',
  'locker.colour': 'Calendar colour',
  'locker.autoColour': 'A colour will be picked automatically.',
  'locker.rentPaid': 'Mark rent as paid',
  'locker.rentPaidBody': 'Next due date will be set to {date}.',

  // visits
  'visit.title': 'Locker visits',
  'visit.log': 'Log visit',
  'visit.logNow': 'Log it',
  'visit.plan': 'Plan a visit',
  'visit.planned': 'Visit planned for {date}',
  'visit.plannedLegend': 'Planned',
  'visit.month': 'Month',
  'visit.week': 'Week',
  'visit.none': 'No visits on this day.',
  'visit.itemsMoved': '{n} moved',
  'visit.whatMoved': 'What moved on this day',
  'visit.locker': 'Bank locker',
  'visit.timeIn': 'Time in',
  'visit.timeOut': 'Time out',
  'visit.timeOrder': 'Time out must be after time in',
  'visit.who': 'Who visited',
  'visit.whoHint': 'E.g. Appa, Amma',
  'visit.purpose': 'Purpose',
  'visit.p.deposit': 'Keep jewellery',
  'visit.p.withdraw': 'Take out jewellery',
  'visit.p.both': 'Keep & take out',
  'visit.p.check': 'Check / inspection',
  'visit.p.rent': 'Rent / bank work',
  'visit.deposited': 'Items kept in locker',
  'visit.withdrawn': 'Items taken out',
  'visit.addDeposit': 'Choose items to keep',
  'visit.addWithdraw': 'Choose items to take out',
  'visit.withdrawWhere': 'Items taken out are now…',
  'visit.pickLockerFirst': 'Choose the locker first',
  'visit.saved': 'Visit saved · {n} items updated',
  'visit.edit': 'Edit visit',
  'visit.editNote': 'Date, time and notes can be changed. Items moved in this visit stay as recorded.',
  'visit.detail': 'Visit',
  'visit.delete': 'Delete visit',
  'visit.noItems': 'None',
  'visit.recent': 'Recent visits',

  // reminders
  'rem.title': 'Reminders',
  'rem.add': 'Add reminder',
  'rem.rent': 'Locker rent due',
  'rem.notReturned': 'Not returned yet',
  'rem.planned': 'Planned visit',
  'rem.custom': 'Reminder',
  'rem.overdue': 'overdue',
  'rem.outSince': 'Out since {date}',
  'rem.done': 'Mark done',
  'rem.rules': 'Reminder rules',
  'rem.rulesBody': 'Remind when an ornament is out of the locker/home for {days} days, and {lead} days before locker rent is due.',
  'rem.notReturnedDays': 'Not returned after',
  'rem.rentLead': 'Rent reminder before',
  'rem.what': 'What to remember',
  'rem.whatHint': 'E.g. Collect chain from repair',
  'rem.lockerOptional': 'Locker (for planned visits)',

  // pickers
  'picker.none': 'No matching ornaments.',
  'picker.done': 'Done ({n} selected)',
  'photo.camera': 'Take photo',
  'photo.gallery': 'Choose from gallery',
  'photo.add': 'Add photos',
  'photo.count': '{n} of {max} photos · long-press a photo for options',
  'photo.countNone': 'No photos yet · up to {max} per ornament',
  'photo.attachBill': 'Attach bill photo',
  'photo.added': '{n} photo(s) attached',
  'photo.full': 'Already {max} photos. Remove one to add another.',
  'photo.makeMain': 'Set as main photo',
  'photo.share': 'Share photo',
  'photo.replace': 'Replace',
  'photo.remove': 'Remove photo',
  'photo.removeBody': 'This photo will be deleted from GoldVault.',

  // settings
  'set.title': 'More',
  'set.language': 'Language',
  'set.general': 'General',
  'set.cloud': 'Google Sheets, export & backup',
  'set.security': 'Security',
  'set.changePin': 'Change PIN',
  'set.currentPin': 'Current PIN',
  'set.newPin': 'New PIN',
  'set.confirmPin': 'New PIN again',
  'set.pinChanged': 'PIN changed',
  'set.biometric': 'Fingerprint / face unlock',
  'set.biometricSub': 'Unlock without typing the PIN',
  'set.biometricNA': 'Not available on this phone',
  'set.blockAll': 'Block screenshots everywhere',
  'set.blockAllSub': 'When off, screenshots are blocked only on screens with values and locker details',
  'set.lockNow': 'Lock now',
  'set.autoLock': 'Locks automatically after 1 minute in the background',
  'set.about': 'About',
  'set.aboutBody': 'Your data stays on this phone in an encrypted database and works fully offline. Internet is used only when you sync to Google Sheets or back up to Google Drive.',

  // cloud
  'cloud.title': 'Sync, export & backup',
  'cloud.subtitle': 'Google Sheets, Excel, PDF and Drive backup',
  'cloud.offlineNote': 'Everything works without internet. These features need internet only while they run.',
  'cloud.account': 'Google account',
  'cloud.signedOut': 'Not signed in',
  'cloud.signIn': 'Sign in with Google',
  'cloud.signOut': 'Sign out',
  'cloud.signOutBody': 'Automatic sync and backup will stop until you sign in again. Your data on this phone is not affected.',
  'cloud.notConfigured': 'Google sign-in is not set up in this build. Ask the person who built the app to add the Google client ID (see README).',
  'cloud.cancelled': 'Sign-in cancelled',
  'cloud.signInFailed': 'Google sign-in failed',
  'cloud.offline': 'No internet connection. Try again when online.',
  'cloud.error': 'Something went wrong',

  // sheets
  'sheet.title': 'Google Sheets',
  'sheet.body': 'The app is the master copy. Your data is copied one way into a Google Sheet called "GoldVault Inventory" (created on first sync), with a tab for every locker.',
  'sheet.never': 'Not synced yet',
  'sheet.last': 'Last synced {date}',
  'sheet.pending': 'Changes waiting to sync',
  'sheet.auto': 'Auto-sync when online',
  'sheet.autoSub': 'Syncs in the background after changes',
  'sheet.syncNow': 'Sync now',
  'sheet.synced': 'Google Sheet updated',
  'sheet.share': 'Share Sheet',
  'sheet.email': 'Email address',
  'sheet.view': 'View only',
  'sheet.edit': 'Can edit',
  'sheet.shareBtn': 'Share',
  'sheet.sharedWith': 'Shared with {email}',
  'sheet.copyLink': 'Copy Sheet link',
  'sheet.copied': 'Link copied',

  // export
  'export.title': 'Export',
  'export.body': 'Create an Excel file or PDF report and share it on WhatsApp, email and more. Works offline.',
  'export.excel': 'Export to Excel (.xlsx)',
  'export.pdf': 'PDF report',

  // backup
  'backup.title': 'Google Drive backup',
  'backup.body': 'Encrypted backup of the full database and all photos to the "GoldVault Backups" folder in your Google Drive. The last 8 backups are kept.',
  'backup.never': 'No backup yet',
  'backup.last': 'Last backup: {date}',
  'backup.passSet': 'Backup password is set',
  'backup.passNotSet': 'Backup password not set',
  'backup.passHelp': 'Needed to restore on a new phone',
  'backup.passTitle': 'Backup password',
  'backup.passWarn': 'Write this password down and keep it safe. Without it, backups cannot be opened – not even by us.',
  'backup.pass': 'Password',
  'backup.passAgain': 'Password again',
  'backup.passShort': 'Use at least 8 characters',
  'backup.weekly': 'Automatic weekly backup',
  'backup.day': 'Day',
  'backup.time': 'Time',
  'backup.wifiOnly': 'Only on Wi-Fi',
  'backup.next': 'Next backup around {date}. If the phone is offline, it runs as soon as it is connected.',
  'backup.now': 'Back up now',
  'backup.restore': 'Restore from Drive',
  'backup.keepNote': 'Restoring replaces all data on this phone with the backup.',
  'backup.none': 'No backups found in Google Drive',
  'backup.choose': 'Choose a backup',
  'backup.enterPass': 'Backup password',
  'backup.restoreWarn': 'All ornaments, lockers, visits and photos on this phone will be replaced by the backup. Continue?',
  'backup.restoreBtn': 'Restore',
  'backup.restored': 'Restored · {n} ornaments',
  'backup.err.no_passphrase': 'Set a backup password first',
  'backup.err.not_signed_in': 'Sign in with Google first',
  'backup.err.wrong_passphrase': 'Wrong backup password',
  'backup.err.bad_file': 'This is not a valid GoldVault backup',

  // notifications
  'notif.rent': 'Locker rent due: {name}',
  'notif.rentBody': 'Due on {date} {amount}',
  'notif.notReturned': 'Ornament not back yet',
  'notif.notReturnedBody': '{name} has been out since {date}',
  'notif.planned': 'Planned locker visit: {name}',
  'notif.plannedBody': 'On {date}',
  'notif.backupDone': 'GoldVault backup complete',
  'notif.backupFailed': 'GoldVault backup needs attention',

  // option labels (codes stored in DB)
  'opt.SBI': 'SBI',
  'opt.HDFC': 'HDFC',
  'opt.ICICI': 'ICICI',
  'opt.Axis': 'Axis',
  'opt.Canara': 'Canara',
  'opt.Union Bank': 'Union Bank',
  'opt.Bank of Baroda': 'Bank of Baroda',
  'opt.Karnataka Bank': 'Karnataka Bank',
  'opt.Other': 'Other',
  'opt.Small': 'Small',
  'opt.Medium': 'Medium',
  'opt.Large': 'Large',
  'opt.Extra Large': 'Extra Large',
  'opt.Gold': 'Gold',
  'opt.Silver': 'Silver',
  'opt.Diamond': 'Diamond',
  'opt.Platinum': 'Platinum',

  // alarms, bank holidays, display settings
  'common.nDays': '{n} d',
  'dash.outNow': 'Out right now',
  'visit.logTab': 'Visit log',
  'visit.remindBack': 'Remind me to put these back',
  'visit.remindBackSub': 'Alarm to keep these ornaments in the locker again',
  'set.display': 'Display',
  'set.showValues': 'Show current prices & estimated value',
  'set.showValuesSub': 'Off: gold/silver rates and values are hidden everywhere (app, PDF, Excel, Sheets)',
  'set.dashBreakdown': 'Dashboard: breakdown',
  'set.dashReminders': 'Dashboard: upcoming reminders',
  'set.dashRecent': 'Dashboard: recent movements',
  'set.autoLockAfter': 'Auto-lock after',
  'set.seconds': '{n} sec',
  'set.minutes': '{n} min',
  'alerts.title': 'Alerts & alarms',
  'alerts.sub': 'Turn each reminder, alarm and holiday alert on or off',
  'alerts.general': 'General',
  'alerts.master': 'All notifications & alarms',
  'alerts.masterSub': 'Master switch for everything below',
  'alerts.time': 'Alert time',
  'alerts.timeSub': 'Time of day for rent, holiday and other date-only alerts',
  'alerts.alarmDefault': 'New reminders ring like an alarm',
  'alerts.exact': 'Allow exact-time alarms',
  'alerts.exactSub': 'Needed on some phones so alarms ring exactly on time',
  'alerts.test': 'Test alarm',
  'alerts.testSub': 'Rings in 1 minute so you can check the sound',
  'alerts.testSet': 'Test alarm will ring in 1 minute',
  'alerts.testTitle': 'GoldVault test alarm',
  'alerts.testBody': 'Alarms are working.',
  'alerts.lockers': 'Lockers & ornaments',
  'alerts.rent': 'Locker rent due',
  'alerts.planned': 'Planned visits',
  'alerts.plannedLead': 'Alert days before visit',
  'alerts.notReturned': 'Ornaments not returned',
  'alerts.holiday': 'Warn before bank holidays',
  'alerts.holidaySub': 'Reminds you to take out jewellery before the bank closes',
  'alerts.holidayLead': 'Warn days before',
  'alerts.holidayWeekends': 'Also warn for normal weekends',
  'alerts.other': 'Other',
  'alerts.backup': 'Backup finished notification',
  'alerts.allOff': 'All notifications and alarms are turned off. Tap to change.',
  'hol.title': 'Bank holidays',
  'hol.add': 'Add holiday',
  'hol.edit': 'Edit holiday',
  'hol.addHere': 'Add holiday on this day',
  'hol.delete': 'Delete holiday',
  'hol.name': 'Holiday name',
  'hol.nameHint': 'E.g. Ugadi, Ayudha Pooja, Deepavali',
  'hol.everyYear': 'Every year',
  'hol.everyYearSub': 'Same date every year (e.g. Republic Day)',
  'hol.on': 'Bank closed on this day',
  'hol.off': 'switched off',
  'hol.open': 'Bank open',
  'hol.closed': 'Bank closed',
  'hol.closedDays': 'Bank closed {n} day(s)',
  'hol.closedThatDay': 'Bank is closed on this day: {why}',
  'hol.alertOn': 'alert on {date}',
  'hol.alertsOff': 'Holiday alerts are switched off (Alerts & alarms).',
  'hol.legendHoliday': 'Bank holiday',
  'hol.legendWeekend': 'Sunday / 2nd & 4th Saturday',
  'hol.upcoming': 'Coming closures',
  'hol.noneUpcoming': 'No bank holidays in the next 4 months.',
  'hol.remindTake': 'Alarm to take jewellery before this',
  'hol.list': 'Holiday list',
  'hol.listHelp': 'Fixed-date holidays are added for you. Festival dates change every year, so add them from your bank\'s holiday list. Switch any holiday off.',
  'hol.ruleSundays': 'Banks closed on all Sundays',
  'hol.ruleSaturdays': 'Banks closed on 2nd & 4th Saturdays',
  'hol.onVisitCal': 'Show bank holidays on visit calendar',
  'hol.weekend': 'Weekend',
  'hol.sun': 'Sunday',
  'hol.sat2': '2nd Saturday',
  'hol.sat4': '4th Saturday',
  'notif.keep': 'Put jewellery back in the locker',
  'notif.take': 'Take jewellery from the locker',
  'notif.holiday': 'Bank closed {n} day(s) from {date}',
  'notif.holidayBody': '{what} ({range}). Take out any jewellery you need before then.',
  'rem.titleSub': 'Alarms to keep / take jewellery, planned visits',
  'rem.mine': 'My alarms & reminders',
  'rem.mineEmpty': 'No alarms yet. Tap "Add reminder" to set one.',
  'rem.auto': 'Automatic alerts',
  'rem.holiday': 'Bank holiday',
  'rem.edit': 'Edit reminder',
  'rem.delete': 'Delete reminder',
  'rem.type': 'What is it for?',
  'rem.kind.keep': 'Keep in locker',
  'rem.kind.take': 'Take from locker',
  'rem.kind.planned_visit': 'Locker visit',
  'rem.kind.custom': 'Other',
  'rem.locker': 'Locker',
  'rem.titleAuto': 'Leave empty for an automatic title',
  'rem.theLocker': 'the locker',
  'rem.keepTitle': 'Keep jewellery in {where}',
  'rem.takeTitle': 'Take jewellery from {where}',
  'rem.repeat': 'Repeat',
  'rem.repeat.none': 'Does not repeat',
  'rem.repeat.weekly': 'Every week',
  'rem.repeat.monthly': 'Every month',
  'rem.repeat.yearly': 'Every year',
  'rem.items': 'Ornaments',
  'rem.chooseItems': 'Choose ornaments (optional)',
  'rem.keepAutoDone': 'Marked done automatically when these ornaments are put in a locker.',
  'rem.alarm': 'Ring like an alarm',
  'rem.alarmSub': 'Loud alarm sound that keeps ringing until you open it',
  'rem.enabled': 'Reminder on',
  'rem.saved': 'Reminder set for {when}',

  // time out of locker / return-by
  'dur.justNow': 'just now',
  'dur.days': '{n} days',
  'dur.hours': '{n} hrs',
  'dur.mins': '{n} min',
  'ret.title': 'Return-by alarm',
  'ret.sub': 'Optional: alarm to put this jewellery back in the locker',
  'ret.date': 'Return by',
  'ret.untilBack': 'Keep reminding every day until put back',
  'ret.untilBackSub': 'After the return date, the alarm repeats daily until it is back in a locker',
  'ret.outFor': 'Out for {d}',
  'ret.by': 'return by {date}',
  'ret.overdue': 'overdue since {date}',
  'ret.takenOutOn': 'Taken out of locker: {date}',
  'ret.setAlarm': 'Set return-by alarm',
  'ret.screen': 'Taken out',
  'ret.screenSub': 'How long each ornament has been out of the locker',
  'ret.none': 'Everything is in the lockers.',
  'ret.summary': '{n} ornaments out of the lockers',
  'ret.lateN': '{n} overdue',
  'ret.askDefault': 'Return-by alarm on by default',
  'ret.askDefaultSub': 'When taking jewellery out, the return-by alarm starts switched on',
  'ret.defaultDays': 'Default return after',
  'set.showOutTime': 'Show how long ornaments are out',
  'set.showOutTimeSub': '"Out for 3 days" on ornament cards',
  'rem.repeat.until_back': 'Every day until put back',
  'rem.repeat.daily': 'Every day',

  // multiple alarm options
  'alert.options': 'Alarm options',
  'alert.alertMe': 'Alert me',
  'alert.atTime': 'At the time',
  'alert.before': '{x} before',
  'alert.inX': 'In {x}',
  'alert.custom': 'Custom…',
  'alert.mins': '{n} min',
  'alert.hours': '{n} hr',
  'alert.days': '{n} day',
  'alert.weeks': '{n} week',
  'alert.unit.min': 'minutes before',
  'alert.unit.hour': 'hours before',
  'alert.unit.day': 'days before',
  'alert.unit.week': 'weeks before',
  'alert.sound': 'Sound',
  'alert.sound.alarm': 'Alarm',
  'alert.sound.notify': 'Sound',
  'alert.sound.silent': 'Silent',
  'alert.soundHelp.alarm': 'Alarm volume; keeps ringing until you open or dismiss it',
  'alert.soundHelp.notify': 'Normal notification sound, once',
  'alert.soundHelp.silent': 'Shows quietly (vibration only, if on)',
  'alert.vibrate': 'Vibrate',
  'alert.snooze': 'Snooze button',
  'alert.snoozeOff': 'Off',
  'alert.defaults': 'Default alarm options',
  'alert.defaultsSub': 'Alert times, sound, vibration and snooze for new reminders',
  'alert.forItem': 'Alarms for this ornament',
  'alert.noneForItem': 'No alarms for this ornament yet.',
  'alert.nAlerts': '{n} alerts',
  'notif.snooze': 'Snooze {n} min',
  'notif.done': 'Done',
};
